// Static, spoiler-light plot prompts for catalogue movies. Keeping these in a
// separate module makes the compact filmography data readable while preserving
// a genuinely movie-specific clue for play.
export const MOVIE_STORY_CLUES: Readonly<Record<string, string>> = {
  "2000:Kalisundam Raa": "An estranged grandson enters his ancestral home under a false identity to reunite a divided family.",
  "2000:Jayam Manadera": "A man raised abroad discovers a village feud and the dangerous legacy waiting for him.",
  "2000:Badri": "A dare sends a supremely confident young man toward the one romance capable of humbling him.",
  "2000:Yuvaraju": "A carefree student's romance collapses when a woman arrives carrying a child and an old claim.",
  "2000:Vamsi": "A fashion designer pursues love while a ruthless industrialist threatens both of their families.",
  "2000:Annayya": "A devoted elder brother sacrifices his happiness to secure a future for his younger siblings.",
  "2000:Nuvve Kavali": "Two lifelong friends remain blind to their love until marriage threatens to separate them.",
  "2000:Chitram": "Two college students face adulthood overnight after an unexpected pregnancy changes their plans.",
  "2000:Azad": "A wanted freedom fighter's name becomes the shield for a man protecting a terrorized community.",
  "2000:Devullu": "Two neglected children seek help from the gods to repair their parents' broken marriage.",
  "2000:Kshemanga Velli Labhamga Randi": "Three debt-ridden families discover that chasing quick money can make home life even costlier.",
  "2000:Chirunavvutho": "A rejected groom masks heartbreak with humour while helping the woman he still loves.",
  "2001:Narasimha Naidu": "A peaceful dance teacher's violent past returns when rival families threaten his village.",
  "2001:Murari": "A young heir races to understand a generational curse before it claims another life.",
  "2001:Kushi": "Two stubborn friends keep hiding their affection behind quarrels, pride, and terrible timing.",
  "2001:Student No. 1": "A convicted young man enters law college determined to fulfil his father's abandoned dream.",
  "2001:Nuvvu Nenu": "Teenage lovers run from families whose class prejudice turns romance into open rebellion.",
  "2001:Anandam": "Four neighbours stumble through friendship and romance while learning to take responsibility.",
  "2001:Manasantha Nuvve": "Childhood sweethearts separated by fate search for the bond neither has forgotten.",
  "2001:Daddy": "A devoted father loses his daughter and must rebuild a family shattered by grief.",
  "2001:Itlu Sravani Subramanyam": "Two strangers planning to die together discover reasons to keep living instead.",
  "2001:Priyamaina Neeku": "A young woman quietly loves her best friend while helping him pursue somebody else.",
  "2001:Hanuman Junction": "Two inseparable strongmen become rivals when friendship and romance collide in their town.",
  "2002:Aadi": "A cheerful student learns why his family was destroyed and returns to reclaim its honour.",
  "2002:Santosham": "A widower attending a wedding confronts the love he lost and the sacrifice behind it.",
  "2002:Nuvvu Leka Nenu Lenu": "Childhood companions realize their constant bickering has always concealed a deeper bond.",
  "2002:Takkari Donga": "A charming outlaw hunts a legendary diamond while avenging the parents he barely knew.",
  "2002:Indra": "A revered faction leader lives incognito after giving up power to end a cycle of revenge.",
  "2002:Jayam": "A timid student must find courage when a violent cousin stands between him and love.",
  "2002:Sontham": "A loyal friend repeatedly helps the woman he loves pursue another man.",
  "2002:Idiot": "A reckless young man falls for a police commissioner's daughter and refuses every warning.",
  "2002:Eeswar": "A hot-headed mechanic resists a wealthy girl's affection while confronting the wounds of poverty.",
  "2002:Nee Sneham": "Two close friends fall for the same woman after one life-changing accident.",
  "2002:Khadgam": "Three men from different worlds are pulled together by terrorism and a shared national identity.",
  "2002:Vasu": "A musician hides his dream from a father who expects him to join the police.",
  "2002:Gemini": "A street rowdy attempts reform for love while an old rival keeps dragging him back.",
  "2002:Allari": "A mischievous tenant turns an apartment community upside down while chasing an unlikely romance.",
  "2002:Nuvve Nuvve": "A possessive father and the unemployed man his daughter loves battle over her future.",
  "2002:Aaduthu Paaduthu": "A compulsive liar creates romantic chaos when one harmless invention grows beyond control.",
  "2003:Dil": "A fearless student challenges a powerful father who refuses to accept his daughter's love.",
  "2003:Amma Nanna O Tamila Ammayi": "An estranged son enters the boxing ring to honour the mother who raised him.",
  "2003:Johnny": "A martial-arts coach enters dangerous fights to pay for his wife's medical treatment.",
  "2003:Nijam": "A timid young man is forced toward vengeance after corruption destroys his innocent father.",
  "2003:Vasantham": "A married man's lifelong friendship with a woman tests trust inside his new home.",
  "2003:Shivamani": "A principled police officer's romance is torn apart by a ruthless criminal network.",
  "2003:Satyam": "An aspiring songwriter struggles for recognition while receiving anonymous encouragement from next door.",
  "2003:Missamma": "An ambitious employee accepts a bizarre contract and enters her boss's carefully hidden domestic life.",
  "2003:Aithe": "Four unemployed friends are unknowingly recruited into a criminal mastermind's hijacking plan.",
  "2003:Gangotri": "A servant's son and a wealthy heiress protect a childhood bond from violent opposition.",
  "2003:Kabaddi Kabaddi": "A playful villager must win both a sporting contest and approval from his lover's family.",
  "2004:Andhrawala": "A labour leader's son returns from abroad and inherits a battle he never knew existed.",
  "2004:Varsham": "Two lovers repeatedly meet in the rain while an obsessed rival closes in on them.",
  "2004:Lakshmi Narasimha": "A transferred police officer confronts the faction lord controlling an entire district.",
  "2004:Venky": "Four reckless friends board a train and become suspects in a murder they did not commit.",
  "2004:Malliswari": "A carefree bank employee unknowingly falls for a princess hiding from assassins.",
  "2004:Gharshana": "A relentless officer hunting an organized gang discovers that love creates his greatest vulnerability.",
  "2004:Shankar Dada MBBS": "A lovable gangster enters medical college to prove himself to his disappointed father.",
  "2004:Anand": "An independent woman rebuilding after tragedy finds companionship in the man next door.",
  "2004:Arjun": "A protective brother battles a powerful family after his twin sister's marriage becomes a trap.",
  "2004:Mass": "An orphan infiltrates a crime lord's world to settle a deeply personal score.",
  "2004:Aa Naluguru": "A principled man devoted to others leaves his family to discover the true worth of his life.",
  "2005:Nuvvostanante Nenoddantana": "A pampered city boy must prove himself as a farmer to earn his love.",
  "2005:Balu": "A feared enforcer's secret promise draws him into protecting a family from its violent past.",
  "2005:Bhadra": "A carefree student shelters his friend's sister after a faction feud wipes out her family.",
  "2005:Andarivaadu": "A working-class father and his polished son navigate family pride, romance, and mistaken identities.",
  "2005:Chatrapathi": "A displaced refugee rises against the men exploiting his community while searching for his mother.",
  "2005:Super": "Two expert thieves and a motorcycle stunt rider circle a fortune hidden behind betrayal.",
  "2005:Anukokunda Oka Roju": "A singer loses an entire day of memory and uncovers a conspiracy while retracing it.",
  "2005:Sankranthi": "Brothers living under one roof learn how easily pride can fracture a close-knit family.",
  "2005:Vennela": "Indian students abroad stumble through friendship, heartbreak, and a romance complicated by the past.",
  "2006:Devadasu": "A poor young man follows a senator's daughter overseas after her father separates them.",
  "2006:Happy": "A reluctant marriage arrangement pushes two quarrelling strangers into an alliance that becomes love.",
  "2006:Style": "A disabled dancer assembles a team to defeat the rival who ended his career.",
  "2006:Sri Ramadasu": "A tax officer devotes royal funds and his freedom to building a temple.",
  "2006:Vikramarkudu": "A petty thief meets a child who mistakes him for her fearless police-officer father.",
  "2006:Godavari": "Two disappointed strangers board a river journey and slowly reconsider life and love.",
  "2006:Rakhi": "A brother takes the law into his own hands after violence reaches his family.",
  "2006:Stalin": "A former soldier starts a chain of kindness that powerful men attempt to crush.",
  "2006:Sainikudu": "A principled young man challenges a corrupt politician after floods expose government failure.",
  "2006:Kithakithalu": "An overweight policeman's unhappy marriage becomes chaos when he falls for another woman.",
  "2007:Desamuduru": "A television reporter rescues a sheltered woman and draws the fury of a crime lord.",
  "2007:Yogi": "A village son enters the underworld while his mother searches the city for him.",
  "2007:Dhee": "A reckless employee tries to unite his boss's sister with the man she loves.",
  "2007:Munna": "A college student challenges the crime boss whose hidden connection explains his painful childhood.",
  "2007:Dubai Seenu": "An ambitious dreamer returns from abroad and finds his friends caught in a murder plot.",
  "2007:Aadavari Matalaku Arthale Verule": "A shy software worker follows love into a household where grief and tradition oppose him.",
  "2007:Chirutha": "A young man released from prison travels abroad to confront his father's killer.",
  "2007:Yamadonga": "A thief dies, argues with the lord of death, and returns with supernatural power.",
  "2007:Tulasi": "A gentle architect's violent family history threatens the wife and child he adores.",
  "2007:Athidhi": "An orphan blamed for murder returns years later to protect the family that once sheltered him.",
  "2007:Mantra": "A woman must spend the night in an allegedly haunted house before she can sell it.",
  "2007:Chandamama": "A village bride's hidden romance complicates the bond between two families.",
  "2007:Anasuya": "A television reporter follows a trail of ritualistic murders toward a killer presumed dead.",
  "2007:Evadaithe Nakenti": "An uncompromising army officer enters politics after corruption strikes his own family.",
  "2008:Krishna": "A former software engineer takes on a city gangster while pursuing an outspoken woman.",
  "2008:Parugu": "A young man helping his friend elope is detained by the bride's furious family.",
  "2008:Bujjigadu": "Childhood sweethearts reunite in Chennai without realizing who the other has become.",
  "2008:Ready": "An accidental abduction pulls a clever young man into an heiress's greedy extended family.",
  "2008:Ullasamga Utsahamga": "A brokenhearted woman slowly trusts love again without recognizing her childhood companion.",
  "2008:Kantri": "An orphan joins a criminal empire while secretly searching for the truth about his family.",
  "2008:Gamyam": "A privileged motorcyclist crosses rural India searching for the woman who rejected him.",
  "2008:Ashta Chamma": "A devoted fan insists on marrying a man with her favourite star's name.",
  "2008:Kotha Bangaru Lokam": "Two teenagers discover first love inside a residential college and face their parents' fears.",
  "2008:King": "An heir returns to a palace of feuding relatives while a lookalike complicates everything.",
  "2008:Nachavule": "A teenager fabricates a romance online and learns painful lessons about trust.",
  "2008:Avakai Biryani": "A migrant auto driver and a pickle seller build small dreams in a quiet town.",
  "2008:Vinayakudu": "A kind, unconventional man slowly wins over a woman trapped in a shallow relationship.",
  "2008:Blade Babji": "A barber and his friends attempt a bank robbery to save their village.",
  "2009:Arundhati": "A modern bride discovers she is the echo of an ancestor who imprisoned a monstrous enemy.",
  "2009:Konchem Ishtam Konchem Kashtam": "A young couple must reunite her estranged parents before they can marry.",
  "2009:Kick": "A thrill-seeker turns crime into adventure while a determined officer hunts him.",
  "2009:Billa": "A small-time thief impersonates a dead international criminal to help the police dismantle his network.",
  "2009:Oy!": "A wealthy drifter brings joy into the carefully ordered life of a terminally ill woman.",
  "2009:Josh": "A college freshman challenges a violent student leader while uncovering his own brother's fate.",
  "2009:Ek Niranjan": "A bounty hunter searching for his parents collides with a powerful criminal family.",
  "2009:Bendu Apparao R.M.P.": "A village quack's comic shortcuts become serious when a dying man's family needs him.",
  "2009:Arya 2": "An obsessive friendship turns dangerous when two men love the same woman.",
  "2009:Village Lo Vinayakudu": "A warm-hearted man visits his lover's village and faces her appearance-conscious father.",
  "2010:Adhurs": "Twins separated at birth grow into a timid priest and a fearless undercover operative.",
  "2010:Leader": "An idealistic heir enters politics after his father's assassination and confronts systemic corruption.",
  "2010:Ye Maaya Chesave": "An aspiring filmmaker falls for his upstairs neighbour despite faith, family, and uncertain feelings.",
  "2010:Bindaas": "A cheerful outsider enters a feuding family and tries to end its cycle of violence.",
  "2010:Simha": "A university lecturer's temper reveals a second identity rooted in an old village conflict.",
  "2010:Darling": "A young man invents an elaborate overseas romance to escape a gangster's marriage proposal.",
  "2010:Vedam": "Five lives from different social worlds converge during one devastating night in the city.",
  "2010:Maryada Ramanna": "A timid man becomes the guest of a family honour-bound to kill him once he leaves.",
  "2010:Brindavanam": "A young man pretends to be his friend's boyfriend and begins healing her divided family.",
  "2010:Khaleja": "A cynical taxi driver is mistaken for the prophesied saviour of a dying village.",
  "2010:Orange": "A man who rejects lifelong promises falls for a woman who believes love must last forever.",
  "2010:Puli": "An upright police officer creates a special team to confront a shadowy national threat.",
  "2010:Prasthanam": "An ambitious stepson struggles for power inside a political dynasty built on blood.",
  "2010:Rakta Charitra": "A grieving son turns revolutionary and builds a violent political empire through revenge.",
  "2010:Betting Bangaraju": "A compulsive gambler wagers that he can make a wealthy bride fall for him.",
  "2011:Ala Modalaindi": "A kidnapped wedding guest recounts the series of near-misses that kept him from love.",
  "2011:Mr. Perfect": "A self-centred perfectionist must decide whether love requires changing for another person.",
  "2011:100% Love": "Two brilliant cousins turn academic rivalry into a romance neither is willing to admit.",
  "2011:Badrinath": "A warrior trained to guard a sacred temple is torn between duty and a devotee's love.",
  "2011:Kandireega": "A street-smart student enters a city college and tangles with rival suitors and gangsters.",
  "2011:Pilla Zamindar": "A spoiled heir must earn a degree under strict conditions before claiming his fortune.",
  "2011:Oosaravelli": "A seemingly carefree stranger pursues criminals according to a promise only he remembers.",
  "2011:Sri Rama Rajyam": "A queen in exile raises her sons while a king confronts the cost of public duty.",
  "2011:Panjaa": "A loyal enforcer questions the criminal family he serves after protecting an innocent woman.",
  "2011:Shakti": "A guide protecting a sacred legacy discovers powers tied to an ancient warrior line.",
  "2011:Golconda High School": "A disgraced cricketer coaches an overlooked school team fighting to save its playground.",
  "2011:Solo": "An orphan longing for a large family falls for a woman whose father distrusts him.",
  "2011:Seema Tapakai": "A rich young man pretends to be poor to impress a woman devoted to charity.",
  "2011:Aha Naa Pellanta!": "A groom wakes after a drunken night and becomes trapped in a stranger's marriage scheme.",
  "2012:Businessman": "An outsider arrives with a plan to turn Mumbai's scattered criminals into one corporation.",
  "2012:Ishq": "A cancelled flight gives two strangers a perfect day before an old rivalry resurfaces.",
  "2012:Julayi": "A sharp drifter who foils a robbery becomes the only obstacle to a brilliant criminal.",
  "2012:Life Is Beautiful": "Young neighbours in a middle-class colony navigate friendship, status, and first love.",
  "2012:Cameraman Gangatho Rambabu": "A hot-headed mechanic becomes a television reporter and confronts a rising political demagogue.",
  "2012:Damarukam": "An ordinary man learns his love is central to a demon's plan for cosmic power.",
  "2012:Krishnam Vande Jagadgurum": "A reluctant theatre performer enters a mining town and discovers his family's buried struggle.",
  "2012:Mithunam": "An elderly couple living alone turn everyday chores and memories into a complete world.",
  "2012:Rebel": "A carefree young man follows a trail of criminals to avenge his murdered family.",
  "2012:Ee Rojullo": "Two cynical young people agree to avoid love and immediately complicate their own rule.",
  "2012:Andala Rakshasi": "A woman caught between memory and survival becomes the centre of two consuming loves.",
  "2012:Avunu": "A newlywed senses an invisible presence in her house while everyone dismisses her fear.",
  "2012:Sudigadu": "An invincible hero races through a universe made from every commercial-cinema cliché.",
  "2012:Poola Rangadu": "A man buys disputed land and must transform himself before the local strongman kills him.",
  "2012:Mem Vayasuku Vacham": "A young man falls for a woman whose family is determined to separate them.",
  "2013:Naayak": "Two identical men unknowingly share enemies, romances, and a war against powerful criminals.",
  "2013:Seethamma Vakitlo Sirimalle Chettu": "Two brothers with opposite temperaments hold their middle-class family together through setbacks.",
  "2013:Mirchi": "A peace-loving young man enters a violent household to change it from within.",
  "2013:Swamy Ra Ra": "A small-time thief and a pickpocket chase a stolen idol through the city's underworld.",
  "2013:Baadshah": "A rejected police aspirant enters the mafia under an extravagant alias to destroy it.",
  "2013:Gunde Jaari Gallanthayyinde": "One wrongly saved phone number sends a confident flirt into a maze of mistaken identity.",
  "2013:Prema Katha Chitram": "Four friends enter an isolated farmhouse intending to die and meet an unexpected resident.",
  "2013:Balupu": "A bank employee's comic romance awakens the dangerous history he left behind.",
  "2013:Uyyala Jampala": "Two bickering cousins in a village fail to recognize that jealousy is love.",
  "2013:Venkatadri Express": "A meticulous young man misses his train and races through a night of escalating detours.",
  "2013:Shadow": "A mysterious vigilante targets an international crime lord responsible for his family's deaths.",
  "2013:Ramayya Vasthavayya": "A charming student enters a household with a hidden revenge plan tied to a massacre.",
  "2013:Potugadu": "A suicidal man trades stories with a stranger about the four romances that ruined him.",
  "2014:1: Nenokkadine": "A rock star with uncertain memories hunts the people he believes murdered his parents.",
  "2014:Yevadu": "A burn survivor wakes with another man's face and uses it to continue a dead stranger's revenge.",
  "2014:Heart Attack": "A commitment-averse traveller gives a woman forty-eight hours to fall for him.",
  "2014:Legend": "A powerful family heir returns from abroad when old faction enemies threaten his people.",
  "2014:Race Gurram": "Two competitive brothers—a reckless drifter and a rigid policeman—collide over the same villain.",
  "2014:Manam": "A child recognizes his late parents in two strangers and tries to reunite them across generations.",
  "2014:Run Raja Run": "A cheerful young man who can detect lies becomes entangled in a kidnapping operation.",
  "2014:Karthikeya": "A medical student investigates why a village temple remains closed after a string of deaths.",
  "2014:Oohalu Gusagusalade": "A television presenter unknowingly coaches his boss to woo the woman he himself loves.",
  "2014:Loukyam": "A clever runaway helps one couple elope, then falls for another woman from the same furious family.",
  "2014:Aagadu": "A theatrical police officer is transferred to a town controlled by a ruthless industrialist.",
  "2014:Rabhasa": "A young man tries to honour his mother's promise by repairing a fractured extended family.",
  "2014:Ala Ela": "An arranged match is derailed by fake identities, old crushes, and a chaotic road trip.",
  "2014:Geethanjali": "A filmmaker rents an apartment with a deadly reputation and meets the spirit haunting it.",
  "2014:Dikkulu Choodaku Ramayya": "A father and son unknowingly compete for the affection of the same young woman.",
  "2015:Gopala Gopala": "An atheist shopkeeper sues God after a disaster, prompting a divine visitor to challenge every side.",
  "2015:Temper": "A corrupt police officer changes course after confronting the brutal consequences of his choices.",
  "2015:Malli Malli Idi Rani Roju": "A runner and a Muslim woman carry one unfinished love across decades of separation.",
  "2015:Yevade Subramanyam": "An ambitious executive treks toward a Himalayan lake and discovers a life beyond success.",
  "2015:S/O Satyamurthy": "A principled son gives up wealth to repay his late father's debts and preserve his name.",
  "2015:Srimanthudu": "A billionaire's restless heir adopts his ancestral village and confronts the forces exploiting it.",
  "2015:Bhale Bhale Magadivoy": "A forgetful botanist hides his condition while trying to sustain a new romance.",
  "2015:Kanche": "Two lovers divided by caste are separated again by a battlefield in wartime Europe.",
  "2015:Kumari 21F": "An insecure young chef cannot accept that the confident woman he loves had a life before him.",
  "2015:Rudhramadevi": "A princess raised publicly as a prince fights to protect her throne and reveal her identity.",
  "2015:Bruce Lee: The Fighter": "A stuntman impersonates a police officer and accidentally enters a dangerous criminal investigation.",
  "2015:Akhil": "A street performer races to protect a sacred object capable of safeguarding the planet.",
  "2015:Cinema Choopistha Mava": "A carefree young man must work under his lover's father to prove he can support her.",
  "2015:Bhale Manchi Roju": "A simple proposal day becomes a criminal chase after a kidnapping goes spectacularly wrong.",
  "2015:Raju Gari Gadhi": "Contestants enter a haunted palace for a television show and awaken its unfinished story.",
  "2015:Kerintha": "A group of college friends learn that youth, loyalty, and romance do not mature at the same pace.",
  "2016:Nannaku Prematho": "A son uses elaborate mind games to avenge the businessman who ruined his dying father.",
  "2016:Soggade Chinni Nayana": "A flirtatious ghost returns to his village to repair his son's marriage and solve his own death.",
  "2016:Oopiri": "A wealthy quadriplegic and the ex-con hired as his caretaker transform each other's lives.",
  "2016:Sardaar Gabbar Singh": "An eccentric policeman arrives in a princely town terrorized by a land-hungry warlord.",
  "2016:Supreme": "A taxi driver protects a gifted child whose inheritance could save an entire charitable trust.",
  "2016:A Aa": "A sheltered young woman visits her mother's relatives and falls for the cousin she cannot openly choose.",
  "2016:Gentleman": "A woman suspects the charming man beside her on a flight may be connected to a murder.",
  "2016:Krishna Gaadi Veera Prema Gaadha": "A timid lover must escort three children through faction country to prove his courage.",
  "2016:Janatha Garage": "An environmental activist inherits the mission of a neighbourhood group that delivers its own justice.",
  "2016:Dhruva": "An idealistic officer chooses the brilliant scientist controlling a criminal network as his ultimate target.",
  "2016:Ekkadiki Pothavu Chinnavada": "A heartbroken programmer meets a mysterious woman whose body may belong to somebody else.",
  "2016:Brahmotsavam": "A young heir follows his late father's roots in an attempt to reunite a sprawling family.",
  "2016:Jyo Achyutananda": "Two married brothers revisit the woman who once came between them.",
  "2016:Kalyana Vaibhogame": "Two marriage-averse strangers accept a wedding plan believing they can escape it later.",
  "2016:Srirastu Subhamastu": "A wealthy young man hides his family background to win love without privilege.",
  "2017:Khaidi No. 150": "A petty thief impersonates an activist and inherits a village's fight against corporate land seizure.",
  "2017:Gautamiputra Satakarni": "An ancient emperor campaigns to unite divided kingdoms under one realm.",
  "2017:Nenu Local": "A carefree graduate decides persistence alone can win a woman already promised to someone else.",
  "2017:The Ghazi Attack": "A submarine crew undertakes a classified underwater mission on the eve of war.",
  "2017:Katamarayudu": "A village strongman who distrusts marriage falls in love and conceals his violent occupation.",
  "2017:Baahubali 2: The Conclusion": "A warrior learns how his royal father lost a throne through loyalty, jealousy, and betrayal.",
  "2017:Fidaa": "A spirited Telangana woman and an American doctor fall in love but refuse to abandon their homes.",
  "2017:Nene Raju Nene Mantri": "A village moneylender enters politics after humiliation and lets ambition consume his marriage.",
  "2017:Jai Lava Kusa": "Three estranged brothers reunite when the most dangerous among them needs the other two.",
  "2017:Mahanubhavudu": "A man obsessed with cleanliness falls in love with a woman from a lively village household.",
  "2017:Raja the Great": "A blind but highly trained young man protects a police officer's daughter from a vengeful gangster.",
  "2017:Shatamanam Bhavati": "An elderly couple stages a separation to bring their distant children home for a festival.",
  "2017:Spyder": "An intelligence officer who secretly monitors calls hunts a killer fascinated by human suffering.",
  "2017:Mental Madhilo": "A chronically indecisive young man meets two women and must finally make an honest choice.",
  "2017:Anando Brahma": "A frightened landlord hires people to prove his supposedly haunted house is safe to sell.",
  "2017:PSV Garuda Vega": "An investigator following a routine murder uncovers an international financial conspiracy.",
  "2018:Agnyaathavaasi": "A billionaire's hidden heir enters his own company to expose the conspiracy behind a murder.",
  "2018:Bhaagamathie": "An imprisoned civil servant is questioned inside an abandoned mansion with a terrifying history.",
  "2018:Tholi Prema": "A volatile young man and an ambitious woman repeatedly meet as their priorities pull them apart.",
  "2018:Bharat Ane Nenu": "A graduate unexpectedly becomes chief minister and attempts to make public accountability unavoidable.",
  "2018:RX 100": "A village youth's passionate romance is retold after heartbreak exposes a devastating deception.",
  "2018:Goodachari": "A rejected intelligence recruit is framed for an attack and must uncover a secret within the agency.",
  "2018:Geetha Govindam": "One disastrous bus encounter makes a mild lecturer look like a predator to the woman he admires.",
  "2018:C/o Kancharapalem": "Four love stories at different ages unfold within one neighbourhood and reveal a shared soul.",
  "2018:Aravinda Sametha Veera Raghava": "A faction heir chooses peace after his father's death but must survive men invested in war.",
  "2018:Taxiwaala": "A struggling driver buys a used car that seems to have a furious will of its own.",
  "2018:Awe!": "Several strangers inside a restaurant turn out to be fragments of one troubled consciousness.",
  "2018:Ee Nagaraniki Emaindi": "Four former friends reunite in Goa to make the short film they abandoned years earlier.",
  "2018:Naa Peru Surya, Naa Illu India": "A gifted soldier with uncontrollable anger must earn a psychologist's certificate to return to duty.",
  "2018:Chi La Sow": "A reluctant arranged meeting stretches through one night as two strangers lower their defences.",
  "2018:Hushaaru": "Four carefree friends build a brewery after heartbreak and adulthood disrupt their plans.",
  "2018:Sammohanam": "An illustrator who dislikes cinema falls for the actress rehearsing inside his family home.",
  "2019:F2: Fun and Frustration": "Two exasperated husbands flee their marriages and discover bachelor freedom is not the rescue promised.",
  "2019:Majili": "A failed cricketer trapped in old heartbreak slowly recognizes the wife who has always supported him.",
  "2019:Chitralahari": "A talented but chronically unsuccessful inventor fights to make one idea—and himself—work.",
  "2019:Maharshi": "A global executive revisits the friend and village his rise to success left behind.",
  "2019:Agent Sai Srinivasa Athreya": "A small-town detective investigates unidentified bodies and uncovers a scheme exploiting grief.",
  "2019:Brochevarevarura": "Three failing students plan a kidnapping for their friend, only for a second crime to overlap it.",
  "2019:Dear Comrade": "A volatile student leader must learn to listen when the woman he loves confronts workplace abuse.",
  "2019:Evaru": "A corrupt officer questioning a murder suspect discovers that every version of the night is manipulated.",
  "2019:Saaho": "An undercover operative enters a futuristic crime city where a stolen fortune has many claimants.",
  "2019:Gang Leader": "A plagiarizing novelist helps five women avenge the loved ones killed in a robbery.",
  "2019:Sye Raa Narasimha Reddy": "A regional chieftain leads an early uprising against colonial rule despite overwhelming odds.",
  "2019:Mathu Vadalara": "A delivery worker's petty theft turns into a locked-room death and a hallucinatory escape.",
  "2019:Prati Roju Pandage": "A grandson returns from abroad to fill his terminally ill grandfather's remaining days with family.",
  "2019:Oh! Baby": "A seventy-year-old woman magically becomes young again and reclaims dreams sacrificed to family.",
  "2019:Vinaya Vidheya Rama": "An orphan raised by four brothers unleashes brutal force when a dictator targets his family.",
  "2019:Mallesham": "A school dropout invents a machine to spare his mother the punishing labour of weaving.",
  "2019:George Reddy": "A brilliant university student becomes a revolutionary leader amid campus violence and inequality.",
  "2019:Raja Vaaru Rani Gaaru": "A shy village boy cannot confess his feelings before life separates him from his first love.",
  "2020:Sarileru Neekevvaru": "An army major carries a fallen colleague's message home and confronts a corrupt politician.",
  "2020:HIT: The First Case": "A traumatized investigator searches for two missing women while his own memories destabilize him.",
  "2020:Bheeshma": "A meme-making bachelor becomes the accidental heir to an organic-farming company under attack.",
  "2020:Colour Photo": "A dark-skinned engineering student and his classmate challenge prejudice surrounding their romance.",
  "2020:Middle Class Melodies": "A young cook moves to town hoping his Bombay chutney can rescue his family's fortunes.",
  "2020:Uma Maheswara Ugra Roopasya": "A mild photographer vows not to wear footwear until he avenges a public humiliation.",
  "2020:V": "A celebrated police officer receives clues from a killer determined to turn murder into a personal contest.",
  "2020:World Famous Lover": "A failing writer transforms his broken relationship into several imagined romances.",
  "2021:Krack": "A hot-blooded police officer's weakness for three ordinary objects connects his battles with multiple criminals.",
  "2021:Uppena": "A fisherman's daughter and a lower-caste boy fall in love beneath her father's violent pride.",
  "2021:Naandhi": "An innocent software engineer tortured in custody searches for justice after years without trial.",
  "2021:Vakeel Saab": "A disillusioned lawyer returns to court to defend three women blamed for resisting assault.",
  "2021:Love Story": "Two migrants carrying caste and childhood trauma build a dance school and a fragile romance.",
  "2021:Most Eligible Bachelor": "A marriage-focused professional meets a stand-up comic who challenges his idea of partnership.",
  "2021:Akhanda": "Separated twins become a reluctant heir and a fierce ascetic protecting the same land.",
  "2021:Shyam Singha Roy": "A filmmaker accused of plagiarism discovers a past life as a rebellious Bengali writer.",
  "2021:Republic": "An idealistic civil servant confronts a political machine that controls an entire district.",
  "2021:Zombie Reddy": "A game developer attending a village wedding finds the region overrun by infected guests.",
  "2021:Raja Raja Chora": "A small-time thief pretending to be a software engineer watches his lies converge.",
  "2021:Tuck Jagadish": "A composed younger brother returns to protect family land after inheritance turns siblings against one another.",
  "2021:SR Kalyanamandapam": "A young man tries to save his family's wedding hall and repair his bond with his father.",
  "2021:Ek Mini Katha": "A man's private insecurity drives him toward increasingly absurd cures before his wedding.",
  "2021:Vivaha Bhojanambu": "A miserly family becomes stranded in their future son-in-law's home during lockdown.",
  "2021:Adbhutham": "Two strangers discover their phones can communicate across different years at the same moment.",
  "2021:Pushpaka Vimanam": "A schoolteacher hides his runaway bride from everyone while becoming entangled in a suspicious death.",
  "2022:Bangarraju": "A charming spirit returns to help his grandson navigate love and a threat to their temple.",
  "2022:DJ Tillu": "A loud, self-styled disc jockey helps a mysterious woman and wakes inside a murder cover-up.",
  "2022:Bheemla Nayak": "An upright policeman and an influential ex-soldier turn one arrest into a war of pride.",
  "2022:Ante Sundaraniki": "An interfaith couple invents matching lies to make their conservative families approve marriage.",
  "2022:Virata Parvam": "A poet's revolutionary writing draws a young woman into the forest and an armed movement.",
  "2022:Karthikeya 2": "A curious doctor follows ancient clues across India to recover a sacred lost object.",
  "2022:Bimbisara": "A ruthless ancient king is transported into the present and forced to confront his legacy.",
  "2022:Oke Oka Jeevitham": "Three friends travel into the past, each hoping to repair the regret shaping his life.",
  "2022:GodFather": "A mysterious power broker emerges after a chief minister's death to protect the leader's daughter.",
  "2022:Masooda": "A single mother and her timid neighbour seek an exorcist when her daughter becomes possessed.",
  "2022:HIT: The Second Case": "A laid-back investigator hunts a killer who assembled one body from multiple victims.",
  "2022:Dhamaka": "Two men from opposite classes appear to compete for one woman while a corporate takeover looms.",
  "2022:18 Pages": "A heartbroken programmer finds a lost diary and falls for its unseen writer through her unfinished journey.",
  "2022:Radhe Shyam": "A renowned palmist who believes love is absent from his destiny meets a woman defying her own prognosis.",
  "2022:Acharya": "A former insurgent enters a temple town to continue a fallen comrade's fight against exploitation.",
  "2022:Liger": "A fighter with a speech impediment leaves home to chase mixed-martial-arts glory.",
  "2022:The Ghost": "A former intelligence officer returns to protect his estranged sister's family from an underworld threat.",
  "2022:Urvasivo Rakshasivo": "A conservative employee and his independent coworker want very different futures from the same romance.",
  "2022:Swathi Muthyam": "A gentle groom's wedding day collapses when a woman arrives with a child connected to him.",
  "2023:Waltair Veerayya": "A smuggler hired for an unofficial extradition uncovers the truth about his estranged police-officer brother.",
  "2023:Veera Simha Reddy": "A son raised abroad returns to discover the faction war and sacrifices surrounding his father.",
  "2023:Writer Padmabhushan": "A failed young author suddenly becomes famous for a novel he did not write.",
  "2023:Sir": "A junior lecturer sent to a rural college fights a business determined to keep education expensive.",
  "2023:Virupaksha": "A visitor investigates ritual deaths in a village sealed off by terror and superstition.",
  "2023:Custody": "An earnest constable must keep a wanted witness alive while both police and criminals pursue them.",
  "2023:Mem Famous": "Three aimless village friends chase online fame and accidentally begin taking responsibility.",
  "2023:Samajavaragamana": "A young man sabotages his father's exams until a new tenant turns their family relationships upside down.",
  "2023:Baby": "Childhood sweethearts change unequally after college, attention, and insecurity enter their relationship.",
  "2023:Bro": "An arrogant executive dies suddenly and bargains with Time for one chance to fix his life.",
  "2023:Miss Shetty Mr Polishetty": "An independent chef asks a stand-up comic to help her become a mother without marriage.",
  "2023:MAD": "Three engineering students turn hostel life into a parade of pranks, friendships, and romantic disasters.",
  "2023:Bhagavanth Kesari": "A guardian trains a reluctant young woman for the army while an old enemy resurfaces.",
  "2023:Keedaa Cola": "A group of desperate misfits finds a cockroach in a soft-drink bottle and attempts corporate blackmail.",
  "2023:Mangalavaaram": "Mysterious deaths expose the secrets of a village where public accusations appear every Tuesday.",
  "2023:Salaar: Part 1 – Ceasefire": "A quiet mechanic enters a brutal hidden kingdom to defend the friend who once protected him.",
  "2023:Agent": "A reckless recruit with no regard for rules is sent after a former intelligence chief.",
  "2023:Adipurush": "An exiled prince crosses into a demon king's realm to rescue his abducted wife.",
  "2023:Bhola Shankar": "A taxi driver searching for his sister's future secretly hunts a trafficking network.",
  "2023:Skanda": "A mysterious student abducts two brides as part of a larger plan against powerful chief ministers.",
  "2023:Bedurulanka 2012": "A sceptic challenges village leaders profiting from panic over the supposed end of the world.",
  "2023:Maa Oori Polimera 2": "A policeman follows occult clues to learn what truly happened to his missing brother.",
  "2024:Guntur Kaaram": "An estranged son is pressured to deny his mother so a political family can protect its inheritance.",
  "2024:Saindhav": "A retired underworld operative returns to crime to afford his daughter's life-saving treatment.",
  "2024:Eagle": "A journalist's investigation into a vanished cotton farmer reveals an international arms vigilante.",
  "2024:Tillu Square": "A flamboyant event manager meets another seductive stranger and walks into an even larger deception.",
  "2024:The Family Star": "A frugal architect supporting a large household clashes with the tenant documenting his life.",
  "2024:Gaami": "An amnesiac ascetic crosses the Himalayas seeking a rare cure for his fear of human touch.",
  "2024:Committee Kurrollu": "Childhood friends reunite for a village festival as politics reopens a fifteen-year-old wound.",
  "2024:Aay": "A carefree village romance collides with caste assumptions and a strategically concealed identity.",
  "2024:Saripodhaa Sanivaaram": "A man who suppresses anger all week releases it only on Saturdays against carefully chosen wrongdoers.",
  "2024:Mathu Vadalara 2": "Two former delivery boys working as special agents stumble into another narcotics-fuelled conspiracy.",
  "2024:Devara: Part 1": "A feared coastal guardian disappears after turning against the smuggling alliance he once enforced.",
  "2024:KA": "A postman in an isolated village discovers that missing letters conceal a recurring mystery.",
  "2024:Pushpa 2: The Rule": "A smuggling king expands his empire while a humiliated police officer wages a personal war.",
  "2024:35 Chinna Katha Kaadu": "A mother who left school early studies mathematics to help her son survive a rigid classroom.",
  "2024:Ambajipeta Marriage Band": "A barber's family confronts caste humiliation after his sister rejects a powerful man's advances.",
  "2024:Prasanna Vadanam": "A man unable to recognize faces witnesses a murder and cannot identify whom he saw.",
  "2024:Maruthi Nagar Subramanyam": "An unemployed father suddenly receives a fortune and pretends it came from a prestigious job.",
  "2024:Janaka Aithe Ganaka": "A careful middle-class man sues a contraceptive company after an unexpected pregnancy.",
  "2024:Zebra": "A bank employee's attempt to fix a small account error pulls him into a criminal financier's game.",
  "2025:Game Changer": "An election officer wages war on corrupt politics while his father's forgotten movement resurfaces.",
  "2025:Daaku Maharaaj": "A mysterious guardian protects a family while his history as a feared outlaw closes in.",
  "2025:Sankranthiki Vasthunam": "A former officer's ex-girlfriend recruits him for a rescue, alarming his fiercely suspicious wife.",
  "2025:Thandel": "A fisherman crossing an international border endures prison while his partner waits at home.",
  "2025:Court: State vs A Nobody": "A junior lawyer defends a young man trapped by a punitive law and a hostile family.",
  "2025:MAD Square": "The engineering friends reunite for a wedding and trigger an international trail of comic trouble.",
  "2025:HIT: The Third Case": "A brutally effective investigator follows a murder network far beyond his usual jurisdiction.",
  "2025:Kuberaa": "A homeless man is recruited into a financial conspiracy and begins questioning the price of survival.",
  "2025:Hari Hara Veera Mallu": "A legendary outlaw accepts a mission to steal a sacred diamond from an imperial court.",
  "2025:Little Hearts": "An academically struggling teenager joins coaching classes and discovers an awkward first romance.",
  "2025:Raju Weds Rambai": "A village couple's love collides with status, family honour, and a wedding nobody accepts.",
  "2025:The Girlfriend": "A college relationship slowly reveals the difference between devotion, dependence, and control.",
  "2025:K-Ramp": "A carefree heir's chaotic romance forces him to confront the responsibilities he avoids.",
  "2025:Subham": "Newly married men discover that their wives become eerily different while watching a television serial.",
  "2025:Single": "A proudly unattached man chases romance while his closest friend keeps complicating every attempt.",
  "2025:Beauty": "A young romance tests how far affection can survive family pressure and social judgement.",
  "2025:Dhandoraa": "A death forces a village to confront the caste customs it has long treated as ordinary.",
  "2026:The RajaSaab": "A carefree heir enters his ancestral estate and finds romance competing with a supernatural presence.",
  "2026:Mana Shankara Vara Prasad Garu": "A determined family man uses wit and force to reunite the people he loves.",
  "2026:Bhartha Mahasayulaku Wignyapthi": "A married man's carefully managed life unravels when desire, suspicion, and domestic truth converge.",
  "2026:Anaganaga Oka Raju": "A boastful small-town bachelor turns a grand wedding plan into an escalating comic adventure.",
  "2026:Nari Nari Naduma Murari": "A charming man caught between two women discovers that indecision has very public consequences.",
  "2026:Funky": "An unpredictable young man treats love and adulthood like one elaborate joke until consequences arrive.",
  "2026:Couple Friendly": "Two young lovers learn that building a life together demands more than effortless chemistry.",
  "2026:Hey Balwanth": "An ordinary man's attempt to solve a family problem becomes a comic test of courage.",
  "2026:Vishnu Vinyasam": "A mild man's unusual scheme sets off confusion across a community of colourful characters.",
  "2026:Mrithyunjay": "A man investigating a disturbing mystery finds mortality itself at the centre of the puzzle.",
  "2026:Ustaad Bhagat Singh": "A rebellious police officer imposes his own justice on a town controlled by intimidation.",
  "2026:Suyodhana": "A man branded by others fights to control the story of his loyalty and ambition.",
  "2026:Biker": "A determined racer puts family, pride, and his own limits on the line for one defining ride.",
  "2026:Raakaasa": "A young man's unruly impulses turn a familiar relationship into an unexpectedly chaotic reckoning.",
  "2026:Dacoit: A Love Story": "Former lovers reunite as outlaws, with betrayal and a dangerous robbery between them.",
  "2026:Bad Boy Karthik": "A reckless young man is forced to protect the family his behaviour repeatedly endangers.",
  "2026:Papam Prathap": "A hapless villager's small mistake becomes a moral and comic crisis for everyone around him.",
  "2026:Gaayapadda Simham": "A wounded man masks old pain with humour until unfinished business demands a response.",
  "2026:Jetlee": "An unlikely fighter enters a criminal scramble where quick thinking matters more than strength.",
  "2026:Sathi Leelavathi": "A woman's apparently settled life exposes secrets when trust inside her marriage begins to fracture.",
  "2026:Peddi": "A gifted village sportsman becomes the centre of a struggle involving pride, power, and his community.",
  "2026:Sing Geetham": "Young musicians discover their voices while a shared performance reshapes their relationships.",
  "2026:Maa Inti Bangaaram": "A woman protecting her household finds strength nobody around her expected her to need.",
  "2026:Nagabandham: The Secret Treasure": "A seeker follows an ancient serpent legend toward a treasure guarded by faith and danger.",
  "2026:Rao Bahadur": "A respected title and a grand household conceal the compromises of a changing social order.",
  "2026:Lenin": "A fierce rural youth turns personal loss into a confrontation with entrenched local power.",
  "2026:Oh..! Sukumari": "An eccentric woman's arrival rearranges the affections and assumptions of everyone around her.",
  "2026:Chennai Love Story": "Two young people negotiate language, distance, and family while building a romance in the city.",
  "2026:Srinivasa Mangapuram": "A passionate relationship unfolds beneath the traditions and tensions of a temple town.",
  "2026:Korean Kanakaraju": "A local man's fascination with a distant culture turns an action problem into cross-cultural comedy.",
  "2001:Mrugaraju": "A renowned hunter enters a forest where a rogue elephant and a buried crime threaten a community.",
  "2001:Sri Manjunatha": "A defiant nonbeliever's compassion draws him toward the deity and devotion he once rejected.",
  "2004:Anji": "A man raised in the wilderness protects a mystical object from an immortal seeking ultimate power.",
  "2005:Jai Chiranjeeva": "A man travels abroad to find the person responsible for a child's death.",
  "2007:Shankar Dada Zindabad": "A gangster guided by visions of a national icon tries nonviolence to win a radio host.",
  "2004:Gudumba Shankar": "A con man infiltrates his lover's arranged marriage and stages an elaborate family deception.",
  "2006:Bangaram": "An ambitious television reporter helps a village woman escape a dangerous forced marriage.",
  "2006:Annavaram": "A protective brother moves to the city and wages war on the men terrorizing his sister.",
  "2011:Teen Maar": "A modern commitment-phobe hears an older man's story of love that survived distance and time.",
  "2002:Bobby": "The children of two bitter political rivals begin a romance that reignites their families' feud.",
  "2004:Naani": "A neglected child is transformed into an adult overnight but retains a ten-year-old's understanding.",
  "2022:Sarkaru Vaari Paata": "A loan agent returns to India to collect a debt and challenges a corrupt financial tycoon.",
  "2001:Ninnu Choodalani": "A young couple separated by hostile parents leave their child's future in unexpected hands.",
  "2001:Subbu": "A rebellious college student changes after falling for a woman carrying her own family burdens.",
  "2002:Allari Ramudu": "A playful heir enters a wealthy household and uncovers the greed dividing its members.",
  "2003:Naaga": "A student leader becomes entangled in a political struggle after injustice reaches his family.",
  "2004:Samba": "An educated faction heir fights to fulfil his father's dream of schooling the poor.",
  "2005:Naa Alludu": "A rejected suitor enters a proud businesswoman's family to dismantle her arrogance from within.",
  "2005:Narasimhudu": "A village protector survives a massacre and returns to punish the faction responsible.",
  "2006:Ashok": "A mechanic's violent resistance to a criminal syndicate costs him his father's trust.",
  "2012:Dammu": "An orphan is adopted as heir to a faction family and expected to resume its blood feud.",
  "2003:Raghavendra": "A hot-headed youth turns toward spirituality after criminals destroy the people closest to him.",
  "2004:Adavi Ramudu": "A tribal protector falls for a wealthy woman and confronts the exploitation of his forest community.",
  "2005:Chakram": "A terminally ill man secretly leaves his lover and brings hope to a troubled neighbourhood.",
  "2006:Pournami": "A dancer must preserve her family's sacred tradition while a mysterious warrior protects her.",
  "2005:Bunny": "A young man enters an enemy's household to reclaim land connected to his mother's sacrifice.",
  "2010:Varudu": "A bride is abducted during an elaborate wedding, forcing the groom into a personal rescue.",
  "2013:Iddarammayilatho": "A guitarist's recovered diary draws two women into a romance shaped by revenge.",
  "2016:Sarrainodu": "A former soldier delivers violent justice until he meets an adversary protected by political power.",
  "2017:Duvvada Jagannadham": "A mild temple cook secretly operates as a vigilante against criminals beyond the law.",
  "2012:Racha": "A gambler accepts a high-stakes romantic challenge and discovers it was designed as a trap.",
  "2013:Toofan": "An uncompromising officer is transferred into a city controlled by an oil-smuggling network.",
  "2014:Govindudu Andarivadele": "A young man raised abroad enters his estranged grandfather's home without revealing who he is.",
  "2001:Eduruleni Manishi": "A wealthy industrialist and his impulsive younger brother become targets of a calculated deception.",
  "2001:Bava Nachadu": "A married man's effort to help his sister-in-law find a match creates suspicion and romantic confusion.",
  "2001:Adhipathi": "A wrongfully imprisoned son rises through the underworld to confront the politician who ruined his family.",
  "2001:Akasa Veedhilo": "Two childhood friends become musicians, then rivals when fame and love pull them apart.",
  "2006:Boss": "A successful executive's affection for his employee threatens both his company and existing relationship.",
  "2007:Don": "A benevolent underworld leader protects his city when a more ruthless syndicate attempts takeover.",
  "2010:Kedi": "A brilliant gambler pursues one final con while an investigator untangles his many identities.",
  "2010:Ragada": "A village fighter enters the city and plays rival gangsters against one another for a hidden purpose.",
  "2011:Rajanna": "A gifted child searches for a king's help while learning of the rebel who was her father.",
  "2013:Bhai": "A trusted enforcer is sent to kill an officer and instead discovers a family connection.",
  "2017:Om Namo Venkatesaya": "A devoted seeker forms a playful spiritual bond with the deity of a sacred hill.",
  "2017:Raju Gari Gadhi 2": "A mentalist investigates a resort haunting and uncovers the injustice binding its spirit.",
  "2018:Officer": "A disciplined investigator enters another city to expose a decorated policeman's criminal empire.",
  "2018:Devadas": "An underworld fugitive forces a timid doctor to treat him, creating an unlikely friendship.",
  "2021:Wild Dog": "An intelligence team tracks the terrorist network behind a series of coordinated bombings.",
  "2024:Naa Saami Ranga": "Two loyal village friends confront an old feud when festival celebrations revive buried violence.",
  "2001:Devi Putrudu": "An archaeologist discovers a submerged city's secret and his own connection to its divine guardian.",
  "2001:Prematho Raa": "A wealthy flirt treats romance as sport until one woman forces him to face its consequences.",
  "2005:Subash Chandra Bose": "A modern man uncovers an ancestor's rebellion against a colonial-era estate owner.",
  "2006:Lakshmi": "A successful businessman protects his family when a ruthless sibling dispute becomes violent.",
  "2008:Chintakayala Ravi": "A bar worker abroad pretends to be a software engineer for an arranged match.",
  "2010:Namo Venkatesa": "A ventriloquist falls for a woman abroad and follows her into a feuding family.",
  "2010:Nagavalli": "A psychiatrist investigates a dancer whose behaviour suggests a royal spirit has returned.",
  "2012:Bodyguard": "A dutiful protector unknowingly falls for the woman he guards through anonymous phone calls.",
  "2013:Masala": "Two friends sustain a web of false identities after one lies his way into employment.",
  "2016:Babu Bangaram": "A compassionate policeman falls for a suspect's daughter while investigating her missing father.",
  "2017:Guru": "A disgraced boxing coach finds a fierce young woman and trains her against a corrupt system.",
  "2019:Venky Mama": "An uncle raises his orphaned nephew despite an astrologer's warning that their bond is dangerous.",
  "2021:Narappa": "A quiet farmer's violent past resurfaces when caste landlords target his surviving son.",
  "2021:Drushyam 2": "A family's carefully buried secret is threatened when police reopen an apparently solved disappearance.",
  "2022:F3: Fun and Frustration": "Two cash-obsessed families chase a wealthy man's missing heir through overlapping deceptions.",
  "2000:Vamsoddharakudu": "A young heir tries to reconcile estranged relatives while protecting the family estate.",
  "2000:Goppinti Alludu": "A clever son-in-law enters a wealthy household and disrupts its proud matriarch's plans.",
  "2001:Bhalevadivi Basu": "A forest officer confronts poachers while an unusual double identity complicates his mission.",
  "2002:Seema Simham": "A fearless outsider enters faction territory and becomes central to a divided family's survival.",
  "2002:Chennakesava Reddy": "A long-imprisoned faction leader returns while his police-officer son investigates the past.",
  "2003:Palnati Brahmanayudu": "A revered village leader protects his people as an old enemy renews a faction war.",
  "2004:Vijayendra Varma": "An amnesiac veteran follows fragments of memory toward the family and mission he lost.",
  "2005:Allari Pidugu": "Twin brothers with opposite temperaments become entangled in the same family conflict.",
  "2006:Veerabhadra": "A stranger enters a faction household seeking marriage while concealing a revenge mission.",
  "2007:Maharadhi": "A cab driver becomes caught between a singer, her past, and a complicated family secret.",
  "2008:Okka Magadu": "A young reformer discovers an elderly freedom fighter is waging war on corrupt leaders.",
  "2008:Pandurangadu": "A pleasure-seeking man loses everything before discovering faith and responsibility.",
  "2009:Mitrudu": "A troubled woman selects a stranger as her husband, believing he can protect her family.",
  "2011:Parama Veera Chakra": "A celebrated actor accepts a patriotic role that begins to mirror a soldier's real sacrifice.",
  "2012:Adhinayakudu": "Three generations of one family confront political enemies across a long regional struggle.",
  "2012:Srimannarayana": "A journalist investigates his father's murder and a fund intended for struggling farmers.",
  "2015:Lion": "A man waking from a coma disputes his identity and searches for the conspiracy behind it.",
  "2016:Dictator": "A quiet supermarket employee reveals a powerful past when criminals threaten his wife's family.",
  "2017:Paisa Vasool": "A reckless local tough is recruited for a police operation against an international gangster.",
  "2018:Jai Simha": "A devoted father accepts humiliation to protect his child until an old conflict resurfaces.",
  "2019:NTR: Kathanayakudu": "A civil servant's son rises from theatre to become one of Telugu cinema's defining stars.",
  "2019:Ruler": "A businessman searching for his identity discovers a past as a police officer feared by criminals.",
  "2009:Ride": "Two young men compete over a motorcycle that represents freedom and employment to each of them.",
  "2009:Snehituda": "A drifter secretly shelters in a woman's home and becomes entwined with her lonely life.",
  "2010:Bheemili Kabaddi Jattu": "An underdog village team chases sporting glory while its captain navigates first love.",
  "2014:Paisa": "A desperate young man finds a bag of election cash and enters a night of political danger.",
  "2014:Aaha Kalyanam": "Two practical friends start a wedding-planning business with one rule against falling in love.",
  "2015:Janda Pai Kapiraju": "An honest man and his violent lookalike collide over a campaign against everyday corruption.",
  "2016:Majnu": "An assistant director recounts two romances while trying to understand which love was real.",
  "2017:Ninnu Kori": "A former lover enters a married couple's home believing their happiness is only an illusion.",
  "2017:MCA": "A lazy young man reluctantly protects his sister-in-law from a transport mafia.",
  "2018:Krishnarjuna Yudham": "A village performer and a rock musician become unlikely doubles in a rescue across Europe.",
  "2002:Avunu Valliddaru Ista Paddaru!": "A man and woman share the same rented room on opposite schedules before ever meeting.",
  "2004:Naa Autograph": "A man revisits the women who shaped him while travelling to invite them to his wedding.",
  "2005:Bhageeratha": "A devoted son fights bureaucracy and crime to fulfil his father's promise of water for a village.",
  "2006:Khatarnak": "A pickpocket is recruited into the police and sent undercover after a criminal gang.",
  "2008:Baladur": "A carefree nephew returns to repair a family divided by pride and an old misunderstanding.",
  "2009:Anjaneyulu": "A television reporter challenges a criminal network after violence claims his mentor.",
  "2010:Don Seenu": "A cinema-obsessed dreamer enters the underworld and tries to outwit two rival crime lords.",
  "2011:Mirapakay": "An undercover officer becomes a college lecturer to reach the daughter of an international criminal.",
  "2012:Nippu": "Two close friends become enemies when a murder accusation collides with family loyalty.",
  "2012:Daruvu": "A street fighter dies prematurely, argues his way out of the afterlife, and returns in another body.",
  "2014:Power": "A police-obsessed young man impersonates an officer and uncovers a connection to a missing cop.",
  "2015:Bengal Tiger": "An attention-seeking graduate enters politics to avenge humiliation and unexpectedly rises through it.",
  "2018:Touch Chesi Chudu": "A businessman who avoids conflict reveals his former police life when children disappear.",
  "2020:Disco Raja": "A frozen body revived by scientists carries the memories and enemies of a forgotten gangster.",
  "2022:Khiladi": "A prisoner tells competing versions of a money-laundering conspiracy to everyone trying to use him.",
  "2022:Ramarao on Duty": "An honest official investigates missing people and discovers a smuggling network behind their disappearance.",
  "2023:Tiger Nageswara Rao": "A notorious thief builds his legend through daring escapes while authorities close around his town.",
  "2024:Mr. Bachchan": "A suspended tax officer returns for a politically sensitive raid on a powerful industrialist.",
};

export function bespokeStoryClueFor(title: string, year: number) {
  return MOVIE_STORY_CLUES[`${year}:${title}`];
}
