export type CatalogLane = "Star vehicle" | "Breakout hit" | "Cult favourite";

export type MovieSeed = readonly [
  title: string,
  year: number,
  lead: string,
  director: string,
  genres: string,
  lane: CatalogLane,
];

// Mainstream Telugu releases from 2000 onward: major-star filmographies,
// breakout successes, enduring cult films, and memorable high-profile flops.
export const CATALOG_ADDITIONS: MovieSeed[] = [
  // 2000–2004
  ["Kalisundam Raa", 2000, "Venkatesh", "Udayasankar", "Family/Drama", "Star vehicle"],
  ["Jayam Manadera", 2000, "Venkatesh", "N. Shankar", "Action/Drama", "Star vehicle"],
  ["Badri", 2000, "Pawan Kalyan", "Puri Jagannadh", "Romance/Drama", "Star vehicle"],
  ["Yuvaraju", 2000, "Mahesh Babu", "Y. V. S. Chowdary", "Romance/Drama", "Star vehicle"],
  ["Vamsi", 2000, "Mahesh Babu", "B. Gopal", "Action/Romance", "Star vehicle"],
  ["Annayya", 2000, "Chiranjeevi", "Muthyala Subbaiah", "Family/Drama", "Star vehicle"],
  ["Nuvve Kavali", 2000, "Tarun", "K. Vijaya Bhaskar", "Romance/Drama", "Breakout hit"],
  ["Chitram", 2000, "Uday Kiran", "Teja", "Romance/Drama", "Breakout hit"],
  ["Azad", 2000, "Nagarjuna", "Tirupathi Swamy", "Action/Drama", "Star vehicle"],
  ["Narasimha Naidu", 2001, "Nandamuri Balakrishna", "B. Gopal", "Action/Drama", "Star vehicle"],
  ["Murari", 2001, "Mahesh Babu", "Krishna Vamsi", "Romance/Fantasy", "Star vehicle"],
  ["Kushi", 2001, "Pawan Kalyan", "S. J. Suryah", "Romance/Comedy", "Star vehicle"],
  ["Student No. 1", 2001, "Jr NTR", "S. S. Rajamouli", "Action/Drama", "Star vehicle"],
  ["Nuvvu Nenu", 2001, "Uday Kiran", "Teja", "Romance/Drama", "Breakout hit"],
  ["Anandam", 2001, "Akash", "Srinu Vaitla", "Romance/Comedy", "Breakout hit"],
  ["Manasantha Nuvve", 2001, "Uday Kiran", "V. N. Aditya", "Romance/Drama", "Breakout hit"],
  ["Daddy", 2001, "Chiranjeevi", "Suresh Krissna", "Family/Drama", "Star vehicle"],
  ["Itlu Sravani Subramanyam", 2001, "Ravi Teja", "Puri Jagannadh", "Romance/Drama", "Cult favourite"],
  ["Aadi", 2002, "Jr NTR", "V. V. Vinayak", "Action/Drama", "Star vehicle"],
  ["Santosham", 2002, "Nagarjuna", "Dasaradh", "Romance/Drama", "Star vehicle"],
  ["Nuvvu Leka Nenu Lenu", 2002, "Tarun", "Kasi Viswanath", "Romance/Drama", "Breakout hit"],
  ["Takkari Donga", 2002, "Mahesh Babu", "Jayanth C. Paranjee", "Western/Action", "Star vehicle"],
  ["Indra", 2002, "Chiranjeevi", "B. Gopal", "Action/Drama", "Star vehicle"],
  ["Jayam", 2002, "Nithiin", "Teja", "Romance/Drama", "Breakout hit"],
  ["Sontham", 2002, "Aryan Rajesh", "Srinu Vaitla", "Romance/Comedy", "Cult favourite"],
  ["Idiot", 2002, "Ravi Teja", "Puri Jagannadh", "Action/Romance", "Star vehicle"],
  ["Eeswar", 2002, "Prabhas", "Jayanth C. Paranjee", "Action/Drama", "Star vehicle"],
  ["Nee Sneham", 2002, "Uday Kiran", "Paruchuri Murali", "Romance/Drama", "Breakout hit"],
  ["Khadgam", 2002, "Srikanth", "Krishna Vamsi", "Drama/Action", "Cult favourite"],
  ["Vasu", 2002, "Venkatesh", "A. Karunakaran", "Romance/Drama", "Star vehicle"],
  ["Gemini", 2002, "Venkatesh", "Saran", "Action/Drama", "Star vehicle"],
  ["Dil", 2003, "Nithiin", "V. V. Vinayak", "Action/Romance", "Breakout hit"],
  ["Amma Nanna O Tamila Ammayi", 2003, "Ravi Teja", "Puri Jagannadh", "Sports/Drama", "Star vehicle"],
  ["Johnny", 2003, "Pawan Kalyan", "Pawan Kalyan", "Action/Drama", "Star vehicle"],
  ["Nijam", 2003, "Mahesh Babu", "Teja", "Action/Drama", "Star vehicle"],
  ["Vasantham", 2003, "Venkatesh", "Vikraman", "Family/Drama", "Star vehicle"],
  ["Shivamani", 2003, "Nagarjuna", "Puri Jagannadh", "Action/Romance", "Star vehicle"],
  ["Satyam", 2003, "Sumanth", "Surya Kiran", "Romance/Drama", "Breakout hit"],
  ["Missamma", 2003, "Bhumika Chawla", "Neelakanta", "Comedy/Drama", "Cult favourite"],
  ["Aithe", 2003, "Mohit Chadda", "Chandra Sekhar Yeleti", "Thriller/Crime", "Cult favourite"],
  ["Gangotri", 2003, "Allu Arjun", "K. Raghavendra Rao", "Romance/Drama", "Star vehicle"],
  ["Andhrawala", 2004, "Jr NTR", "Puri Jagannadh", "Action/Drama", "Star vehicle"],
  ["Varsham", 2004, "Prabhas", "Sobhan", "Action/Romance", "Star vehicle"],
  ["Lakshmi Narasimha", 2004, "Nandamuri Balakrishna", "Jayanth C. Paranjee", "Action/Drama", "Star vehicle"],
  ["Venky", 2004, "Ravi Teja", "Srinu Vaitla", "Comedy/Crime", "Star vehicle"],
  ["Malliswari", 2004, "Venkatesh", "K. Vijaya Bhaskar", "Romance/Comedy", "Star vehicle"],
  ["Gharshana", 2004, "Venkatesh", "Gautham Vasudev Menon", "Action/Romance", "Star vehicle"],
  ["Shankar Dada MBBS", 2004, "Chiranjeevi", "Jayanth C. Paranjee", "Comedy/Drama", "Star vehicle"],
  ["Anand", 2004, "Raja", "Sekhar Kammula", "Romance/Drama", "Cult favourite"],
  ["Arjun", 2004, "Mahesh Babu", "Gunasekhar", "Action/Drama", "Star vehicle"],
  ["Mass", 2004, "Nagarjuna", "Raghava Lawrence", "Action/Drama", "Star vehicle"],
  ["Aa Naluguru", 2004, "Rajendra Prasad", "Chandra Siddhartha", "Drama/Family", "Cult favourite"],

  // 2005–2009
  ["Nuvvostanante Nenoddantana", 2005, "Siddharth", "Prabhu Deva", "Romance/Drama", "Breakout hit"],
  ["Balu", 2005, "Pawan Kalyan", "A. Karunakaran", "Action/Romance", "Star vehicle"],
  ["Bhadra", 2005, "Ravi Teja", "Boyapati Srinu", "Action/Romance", "Star vehicle"],
  ["Andarivaadu", 2005, "Chiranjeevi", "Srinu Vaitla", "Action/Comedy", "Star vehicle"],
  ["Chatrapathi", 2005, "Prabhas", "S. S. Rajamouli", "Action/Drama", "Star vehicle"],
  ["Super", 2005, "Nagarjuna", "Puri Jagannadh", "Action/Thriller", "Star vehicle"],
  ["Anukokunda Oka Roju", 2005, "Charmy Kaur", "Chandra Sekhar Yeleti", "Thriller/Mystery", "Cult favourite"],
  ["Sankranthi", 2005, "Venkatesh", "Muppalaneni Shiva", "Family/Drama", "Star vehicle"],
  ["Devadasu", 2006, "Ram Pothineni", "Y. V. S. Chowdary", "Romance/Drama", "Breakout hit"],
  ["Happy", 2006, "Allu Arjun", "A. Karunakaran", "Romance/Comedy", "Star vehicle"],
  ["Style", 2006, "Raghava Lawrence", "Raghava Lawrence", "Dance/Drama", "Breakout hit"],
  ["Sri Ramadasu", 2006, "Nagarjuna", "K. Raghavendra Rao", "Devotional/Drama", "Star vehicle"],
  ["Vikramarkudu", 2006, "Ravi Teja", "S. S. Rajamouli", "Action/Comedy", "Star vehicle"],
  ["Godavari", 2006, "Sumanth", "Sekhar Kammula", "Romance/Drama", "Cult favourite"],
  ["Rakhi", 2006, "Jr NTR", "Krishna Vamsi", "Action/Drama", "Star vehicle"],
  ["Stalin", 2006, "Chiranjeevi", "A. R. Murugadoss", "Action/Drama", "Star vehicle"],
  ["Sainikudu", 2006, "Mahesh Babu", "Gunasekhar", "Action/Drama", "Star vehicle"],
  ["Desamuduru", 2007, "Allu Arjun", "Puri Jagannadh", "Action/Romance", "Star vehicle"],
  ["Yogi", 2007, "Prabhas", "V. V. Vinayak", "Action/Drama", "Star vehicle"],
  ["Dhee", 2007, "Vishnu Manchu", "Srinu Vaitla", "Action/Comedy", "Breakout hit"],
  ["Munna", 2007, "Prabhas", "Vamshi Paidipally", "Action/Drama", "Star vehicle"],
  ["Dubai Seenu", 2007, "Ravi Teja", "Srinu Vaitla", "Action/Comedy", "Star vehicle"],
  ["Aadavari Matalaku Arthale Verule", 2007, "Venkatesh", "Selvaraghavan", "Romance/Drama", "Star vehicle"],
  ["Chirutha", 2007, "Ram Charan", "Puri Jagannadh", "Action/Romance", "Star vehicle"],
  ["Yamadonga", 2007, "Jr NTR", "S. S. Rajamouli", "Fantasy/Action", "Star vehicle"],
  ["Tulasi", 2007, "Venkatesh", "Boyapati Srinu", "Action/Drama", "Star vehicle"],
  ["Athidhi", 2007, "Mahesh Babu", "Surender Reddy", "Action/Thriller", "Star vehicle"],
  ["Mantra", 2007, "Charmy Kaur", "Tulasi Ram", "Horror/Thriller", "Breakout hit"],
  ["Krishna", 2008, "Ravi Teja", "V. V. Vinayak", "Action/Comedy", "Star vehicle"],
  ["Parugu", 2008, "Allu Arjun", "Bhaskar", "Romance/Drama", "Star vehicle"],
  ["Bujjigadu", 2008, "Prabhas", "Puri Jagannadh", "Action/Romance", "Star vehicle"],
  ["Ready", 2008, "Ram Pothineni", "Srinu Vaitla", "Romance/Comedy", "Star vehicle"],
  ["Ullasamga Utsahamga", 2008, "Yasho Sagar", "A. Karunakaran", "Romance/Comedy", "Breakout hit"],
  ["Kantri", 2008, "Jr NTR", "Meher Ramesh", "Action/Drama", "Star vehicle"],
  ["Gamyam", 2008, "Sharwanand", "Krish Jagarlamudi", "Road/Drama", "Cult favourite"],
  ["Ashta Chamma", 2008, "Nani", "Mohana Krishna Indraganti", "Romance/Comedy", "Breakout hit"],
  ["Kotha Bangaru Lokam", 2008, "Varun Sandesh", "Srikanth Addala", "Romance/Drama", "Breakout hit"],
  ["King", 2008, "Nagarjuna", "Srinu Vaitla", "Action/Comedy", "Star vehicle"],
  ["Nachavule", 2008, "Tanish", "Ravi Babu", "Romance/Drama", "Breakout hit"],
  ["Arundhati", 2009, "Anushka Shetty", "Kodi Ramakrishna", "Fantasy/Horror", "Breakout hit"],
  ["Konchem Ishtam Konchem Kashtam", 2009, "Siddharth", "Kishore Kumar Pardasani", "Romance/Comedy", "Cult favourite"],
  ["Kick", 2009, "Ravi Teja", "Surender Reddy", "Action/Comedy", "Star vehicle"],
  ["Billa", 2009, "Prabhas", "Meher Ramesh", "Action/Thriller", "Star vehicle"],
  ["Oy!", 2009, "Siddharth", "Anand Ranga", "Romance/Drama", "Cult favourite"],
  ["Josh", 2009, "Naga Chaitanya", "Vasu Varma", "Action/Drama", "Star vehicle"],
  ["Ek Niranjan", 2009, "Prabhas", "Puri Jagannadh", "Action/Romance", "Star vehicle"],
  ["Bendu Apparao R.M.P.", 2009, "Allari Naresh", "E. V. V. Satyanarayana", "Comedy/Drama", "Breakout hit"],
  ["Arya 2", 2009, "Allu Arjun", "Sukumar", "Romance/Drama", "Star vehicle"],

  // 2010–2014
  ["Adhurs", 2010, "Jr NTR", "V. V. Vinayak", "Action/Comedy", "Star vehicle"],
  ["Leader", 2010, "Rana Daggubati", "Sekhar Kammula", "Political/Drama", "Breakout hit"],
  ["Ye Maaya Chesave", 2010, "Naga Chaitanya", "Gautham Vasudev Menon", "Romance/Drama", "Breakout hit"],
  ["Bindaas", 2010, "Manchu Manoj", "Veeru Potla", "Action/Comedy", "Breakout hit"],
  ["Simha", 2010, "Nandamuri Balakrishna", "Boyapati Srinu", "Action/Drama", "Star vehicle"],
  ["Darling", 2010, "Prabhas", "A. Karunakaran", "Romance/Comedy", "Star vehicle"],
  ["Vedam", 2010, "Allu Arjun", "Krish Jagarlamudi", "Drama/Anthology", "Cult favourite"],
  ["Maryada Ramanna", 2010, "Sunil", "S. S. Rajamouli", "Comedy/Thriller", "Breakout hit"],
  ["Brindavanam", 2010, "Jr NTR", "Vamshi Paidipally", "Romance/Comedy", "Star vehicle"],
  ["Khaleja", 2010, "Mahesh Babu", "Trivikram Srinivas", "Action/Fantasy", "Cult favourite"],
  ["Orange", 2010, "Ram Charan", "Bhaskar", "Romance/Drama", "Cult favourite"],
  ["Puli", 2010, "Pawan Kalyan", "S. J. Suryah", "Action/Drama", "Star vehicle"],
  ["Prasthanam", 2010, "Sharwanand", "Deva Katta", "Political/Drama", "Cult favourite"],
  ["Rakta Charitra", 2010, "Vivek Oberoi", "Ram Gopal Varma", "Crime/Drama", "Cult favourite"],
  ["Ala Modalaindi", 2011, "Nani", "Nandini Reddy", "Romance/Comedy", "Breakout hit"],
  ["Mr. Perfect", 2011, "Prabhas", "Dasaradh", "Romance/Drama", "Star vehicle"],
  ["100% Love", 2011, "Naga Chaitanya", "Sukumar", "Romance/Comedy", "Star vehicle"],
  ["Badrinath", 2011, "Allu Arjun", "V. V. Vinayak", "Action/Fantasy", "Star vehicle"],
  ["Kandireega", 2011, "Ram Pothineni", "Santosh Srinivas", "Action/Comedy", "Star vehicle"],
  ["Pilla Zamindar", 2011, "Nani", "G. Ashok", "Comedy/Drama", "Cult favourite"],
  ["Oosaravelli", 2011, "Jr NTR", "Surender Reddy", "Action/Thriller", "Star vehicle"],
  ["Sri Rama Rajyam", 2011, "Nandamuri Balakrishna", "Bapu", "Mythology/Drama", "Star vehicle"],
  ["Panjaa", 2011, "Pawan Kalyan", "Vishnuvardhan", "Action/Thriller", "Cult favourite"],
  ["Shakti", 2011, "Jr NTR", "Meher Ramesh", "Action/Fantasy", "Star vehicle"],
  ["Businessman", 2012, "Mahesh Babu", "Puri Jagannadh", "Crime/Action", "Star vehicle"],
  ["Ishq", 2012, "Nithiin", "Vikram Kumar", "Romance/Drama", "Breakout hit"],
  ["Julayi", 2012, "Allu Arjun", "Trivikram Srinivas", "Action/Comedy", "Star vehicle"],
  ["Life Is Beautiful", 2012, "Abijeet", "Sekhar Kammula", "Coming-of-age/Drama", "Breakout hit"],
  ["Cameraman Gangatho Rambabu", 2012, "Pawan Kalyan", "Puri Jagannadh", "Political/Action", "Star vehicle"],
  ["Damarukam", 2012, "Nagarjuna", "Srinivasa Reddy", "Fantasy/Action", "Star vehicle"],
  ["Krishnam Vande Jagadgurum", 2012, "Rana Daggubati", "Krish Jagarlamudi", "Action/Drama", "Cult favourite"],
  ["Mithunam", 2012, "S. P. Balasubrahmanyam", "Tanikella Bharani", "Drama/Family", "Cult favourite"],
  ["Rebel", 2012, "Prabhas", "Raghava Lawrence", "Action/Drama", "Star vehicle"],
  ["Naayak", 2013, "Ram Charan", "V. V. Vinayak", "Action/Comedy", "Star vehicle"],
  ["Seethamma Vakitlo Sirimalle Chettu", 2013, "Venkatesh & Mahesh Babu", "Srikanth Addala", "Family/Drama", "Star vehicle"],
  ["Mirchi", 2013, "Prabhas", "Koratala Siva", "Action/Drama", "Star vehicle"],
  ["Swamy Ra Ra", 2013, "Nikhil Siddhartha", "Sudheer Varma", "Crime/Comedy", "Breakout hit"],
  ["Baadshah", 2013, "Jr NTR", "Srinu Vaitla", "Action/Comedy", "Star vehicle"],
  ["Gunde Jaari Gallanthayyinde", 2013, "Nithiin", "Vijay Kumar Konda", "Romance/Comedy", "Breakout hit"],
  ["Prema Katha Chitram", 2013, "Sudheer Babu", "J. Prabhakar Reddy", "Horror/Comedy", "Breakout hit"],
  ["Balupu", 2013, "Ravi Teja", "Gopichand Malineni", "Action/Comedy", "Star vehicle"],
  ["Uyyala Jampala", 2013, "Raj Tarun", "Virinchi Varma", "Romance/Drama", "Breakout hit"],
  ["Venkatadri Express", 2013, "Sundeep Kishan", "Merlapaka Gandhi", "Comedy/Romance", "Breakout hit"],
  ["Shadow", 2013, "Venkatesh", "Meher Ramesh", "Action/Thriller", "Star vehicle"],
  ["Ramayya Vasthavayya", 2013, "Jr NTR", "Harish Shankar", "Action/Drama", "Star vehicle"],
  ["1: Nenokkadine", 2014, "Mahesh Babu", "Sukumar", "Action/Thriller", "Cult favourite"],
  ["Yevadu", 2014, "Ram Charan", "Vamshi Paidipally", "Action/Thriller", "Star vehicle"],
  ["Heart Attack", 2014, "Nithiin", "Puri Jagannadh", "Romance/Drama", "Star vehicle"],
  ["Legend", 2014, "Nandamuri Balakrishna", "Boyapati Srinu", "Action/Drama", "Star vehicle"],
  ["Race Gurram", 2014, "Allu Arjun", "Surender Reddy", "Action/Comedy", "Star vehicle"],
  ["Manam", 2014, "Akkineni family", "Vikram Kumar", "Fantasy/Drama", "Star vehicle"],
  ["Run Raja Run", 2014, "Sharwanand", "Sujeeth", "Romance/Comedy", "Breakout hit"],
  ["Karthikeya", 2014, "Nikhil Siddhartha", "Chandoo Mondeti", "Mystery/Thriller", "Breakout hit"],
  ["Oohalu Gusagusalade", 2014, "Naga Shaurya", "Srinivas Avasarala", "Romance/Comedy", "Breakout hit"],
  ["Loukyam", 2014, "Gopichand", "Sriwass", "Action/Comedy", "Star vehicle"],
  ["Aagadu", 2014, "Mahesh Babu", "Srinu Vaitla", "Action/Comedy", "Star vehicle"],
  ["Rabhasa", 2014, "Jr NTR", "Santosh Srinivas", "Action/Comedy", "Star vehicle"],

  // 2015–2019
  ["Gopala Gopala", 2015, "Venkatesh & Pawan Kalyan", "Kishore Kumar Pardasani", "Comedy/Drama", "Star vehicle"],
  ["Temper", 2015, "Jr NTR", "Puri Jagannadh", "Action/Drama", "Star vehicle"],
  ["Malli Malli Idi Rani Roju", 2015, "Sharwanand", "Kranthi Madhav", "Romance/Drama", "Cult favourite"],
  ["Yevade Subramanyam", 2015, "Nani", "Nag Ashwin", "Adventure/Drama", "Breakout hit"],
  ["S/O Satyamurthy", 2015, "Allu Arjun", "Trivikram Srinivas", "Family/Drama", "Star vehicle"],
  ["Srimanthudu", 2015, "Mahesh Babu", "Koratala Siva", "Action/Drama", "Star vehicle"],
  ["Bhale Bhale Magadivoy", 2015, "Nani", "Maruthi", "Romance/Comedy", "Breakout hit"],
  ["Kanche", 2015, "Varun Tej", "Krish Jagarlamudi", "War/Romance", "Cult favourite"],
  ["Kumari 21F", 2015, "Raj Tarun", "Palnati Surya Pratap", "Romance/Drama", "Breakout hit"],
  ["Rudhramadevi", 2015, "Anushka Shetty", "Gunasekhar", "Historical/Action", "Star vehicle"],
  ["Bruce Lee: The Fighter", 2015, "Ram Charan", "Srinu Vaitla", "Action/Comedy", "Star vehicle"],
  ["Akhil", 2015, "Akhil Akkineni", "V. V. Vinayak", "Action/Fantasy", "Star vehicle"],
  ["Nannaku Prematho", 2016, "Jr NTR", "Sukumar", "Action/Drama", "Star vehicle"],
  ["Soggade Chinni Nayana", 2016, "Nagarjuna", "Kalyan Krishna Kurasala", "Fantasy/Comedy", "Star vehicle"],
  ["Oopiri", 2016, "Nagarjuna", "Vamshi Paidipally", "Comedy/Drama", "Star vehicle"],
  ["Sardaar Gabbar Singh", 2016, "Pawan Kalyan", "K. S. Ravindra", "Action/Comedy", "Star vehicle"],
  ["Supreme", 2016, "Sai Dharam Tej", "Anil Ravipudi", "Action/Comedy", "Star vehicle"],
  ["A Aa", 2016, "Nithiin", "Trivikram Srinivas", "Romance/Comedy", "Star vehicle"],
  ["Gentleman", 2016, "Nani", "Mohana Krishna Indraganti", "Romance/Thriller", "Breakout hit"],
  ["Krishna Gaadi Veera Prema Gaadha", 2016, "Nani", "Hanu Raghavapudi", "Romance/Comedy", "Breakout hit"],
  ["Janatha Garage", 2016, "Jr NTR", "Koratala Siva", "Action/Drama", "Star vehicle"],
  ["Dhruva", 2016, "Ram Charan", "Surender Reddy", "Action/Thriller", "Star vehicle"],
  ["Ekkadiki Pothavu Chinnavada", 2016, "Nikhil Siddhartha", "Vi Anand", "Fantasy/Thriller", "Breakout hit"],
  ["Brahmotsavam", 2016, "Mahesh Babu", "Srikanth Addala", "Family/Drama", "Star vehicle"],
  ["Khaidi No. 150", 2017, "Chiranjeevi", "V. V. Vinayak", "Action/Drama", "Star vehicle"],
  ["Gautamiputra Satakarni", 2017, "Nandamuri Balakrishna", "Krish Jagarlamudi", "Historical/Action", "Star vehicle"],
  ["Nenu Local", 2017, "Nani", "Trinadha Rao Nakkina", "Romance/Comedy", "Star vehicle"],
  ["The Ghazi Attack", 2017, "Rana Daggubati", "Sankalp Reddy", "War/Thriller", "Breakout hit"],
  ["Katamarayudu", 2017, "Pawan Kalyan", "Kishore Kumar Pardasani", "Action/Comedy", "Star vehicle"],
  ["Baahubali 2: The Conclusion", 2017, "Prabhas", "S. S. Rajamouli", "Epic/Action", "Star vehicle"],
  ["Fidaa", 2017, "Varun Tej", "Sekhar Kammula", "Romance/Drama", "Breakout hit"],
  ["Nene Raju Nene Mantri", 2017, "Rana Daggubati", "Teja", "Political/Drama", "Star vehicle"],
  ["Jai Lava Kusa", 2017, "Jr NTR", "K. S. Ravindra", "Action/Drama", "Star vehicle"],
  ["Mahanubhavudu", 2017, "Sharwanand", "Maruthi", "Romance/Comedy", "Breakout hit"],
  ["Raja the Great", 2017, "Ravi Teja", "Anil Ravipudi", "Action/Comedy", "Star vehicle"],
  ["Shatamanam Bhavati", 2017, "Sharwanand", "Satish Vegesna", "Family/Drama", "Breakout hit"],
  ["Spyder", 2017, "Mahesh Babu", "A. R. Murugadoss", "Action/Thriller", "Star vehicle"],
  ["Agnyaathavaasi", 2018, "Pawan Kalyan", "Trivikram Srinivas", "Action/Drama", "Star vehicle"],
  ["Bhaagamathie", 2018, "Anushka Shetty", "G. Ashok", "Horror/Thriller", "Star vehicle"],
  ["Tholi Prema", 2018, "Varun Tej", "Venky Atluri", "Romance/Drama", "Breakout hit"],
  ["Bharat Ane Nenu", 2018, "Mahesh Babu", "Koratala Siva", "Political/Drama", "Star vehicle"],
  ["RX 100", 2018, "Kartikeya Gummakonda", "Ajay Bhupathi", "Romance/Drama", "Breakout hit"],
  ["Goodachari", 2018, "Adivi Sesh", "Sashi Kiran Tikka", "Spy/Thriller", "Breakout hit"],
  ["Geetha Govindam", 2018, "Vijay Deverakonda", "Parasuram", "Romance/Comedy", "Breakout hit"],
  ["C/o Kancharapalem", 2018, "Subba Rao", "Venkatesh Maha", "Anthology/Drama", "Cult favourite"],
  ["Aravinda Sametha Veera Raghava", 2018, "Jr NTR", "Trivikram Srinivas", "Action/Drama", "Star vehicle"],
  ["Taxiwaala", 2018, "Vijay Deverakonda", "Rahul Sankrityan", "Fantasy/Comedy", "Breakout hit"],
  ["Awe!", 2018, "Kajal Aggarwal", "Prasanth Varma", "Psychological/Drama", "Cult favourite"],
  ["Ee Nagaraniki Emaindi", 2018, "Vishwak Sen", "Tharun Bhascker", "Comedy/Drama", "Cult favourite"],
  ["Naa Peru Surya, Naa Illu India", 2018, "Allu Arjun", "Vakkantham Vamsi", "Action/Drama", "Star vehicle"],
  ["F2: Fun and Frustration", 2019, "Venkatesh & Varun Tej", "Anil Ravipudi", "Comedy/Drama", "Star vehicle"],
  ["Majili", 2019, "Naga Chaitanya", "Shiva Nirvana", "Romance/Drama", "Breakout hit"],
  ["Chitralahari", 2019, "Sai Dharam Tej", "Kishore Tirumala", "Drama/Romance", "Breakout hit"],
  ["Maharshi", 2019, "Mahesh Babu", "Vamshi Paidipally", "Drama/Action", "Star vehicle"],
  ["Agent Sai Srinivasa Athreya", 2019, "Naveen Polishetty", "Swaroop RSJ", "Mystery/Comedy", "Breakout hit"],
  ["Brochevarevarura", 2019, "Sree Vishnu", "Vivek Athreya", "Crime/Comedy", "Cult favourite"],
  ["Dear Comrade", 2019, "Vijay Deverakonda", "Bharat Kamma", "Romance/Drama", "Cult favourite"],
  ["Evaru", 2019, "Adivi Sesh", "Venkat Ramji", "Crime/Thriller", "Breakout hit"],
  ["Saaho", 2019, "Prabhas", "Sujeeth", "Action/Thriller", "Star vehicle"],
  ["Gang Leader", 2019, "Nani", "Vikram Kumar", "Crime/Comedy", "Star vehicle"],
  ["Sye Raa Narasimha Reddy", 2019, "Chiranjeevi", "Surender Reddy", "Historical/Action", "Star vehicle"],
  ["Mathu Vadalara", 2019, "Sri Simha", "Ritesh Rana", "Crime/Comedy", "Cult favourite"],
  ["Prati Roju Pandage", 2019, "Sai Dharam Tej", "Maruthi", "Family/Comedy", "Breakout hit"],
  ["Oh! Baby", 2019, "Samantha Ruth Prabhu", "Nandini Reddy", "Fantasy/Comedy", "Breakout hit"],
  ["Vinaya Vidheya Rama", 2019, "Ram Charan", "Boyapati Srinu", "Action/Drama", "Star vehicle"],

  // 2020–2025
  ["Sarileru Neekevvaru", 2020, "Mahesh Babu", "Anil Ravipudi", "Action/Comedy", "Star vehicle"],
  ["HIT: The First Case", 2020, "Vishwak Sen", "Sailesh Kolanu", "Crime/Thriller", "Breakout hit"],
  ["Bheeshma", 2020, "Nithiin", "Venky Kudumula", "Romance/Comedy", "Star vehicle"],
  ["Colour Photo", 2020, "Suhas", "Sandeep Raj", "Romance/Drama", "Breakout hit"],
  ["Middle Class Melodies", 2020, "Anand Deverakonda", "Vinod Anantoju", "Comedy/Drama", "Cult favourite"],
  ["Uma Maheswara Ugra Roopasya", 2020, "Satyadev", "Venkatesh Maha", "Comedy/Drama", "Cult favourite"],
  ["V", 2020, "Nani", "Mohana Krishna Indraganti", "Action/Thriller", "Star vehicle"],
  ["World Famous Lover", 2020, "Vijay Deverakonda", "Kranthi Madhav", "Romance/Drama", "Star vehicle"],
  ["Krack", 2021, "Ravi Teja", "Gopichand Malineni", "Action/Drama", "Star vehicle"],
  ["Uppena", 2021, "Panja Vaisshnav Tej", "Buchi Babu Sana", "Romance/Drama", "Breakout hit"],
  ["Naandhi", 2021, "Allari Naresh", "Vijay Kanakamedala", "Legal/Drama", "Breakout hit"],
  ["Vakeel Saab", 2021, "Pawan Kalyan", "Venu Sriram", "Legal/Drama", "Star vehicle"],
  ["Love Story", 2021, "Naga Chaitanya", "Sekhar Kammula", "Romance/Drama", "Breakout hit"],
  ["Most Eligible Bachelor", 2021, "Akhil Akkineni", "Bommarillu Bhaskar", "Romance/Comedy", "Star vehicle"],
  ["Akhanda", 2021, "Nandamuri Balakrishna", "Boyapati Srinu", "Action/Drama", "Star vehicle"],
  ["Shyam Singha Roy", 2021, "Nani", "Rahul Sankrityan", "Period/Drama", "Star vehicle"],
  ["Republic", 2021, "Sai Dharam Tej", "Deva Katta", "Political/Drama", "Cult favourite"],
  ["Zombie Reddy", 2021, "Teja Sajja", "Prasanth Varma", "Horror/Comedy", "Breakout hit"],
  ["Raja Raja Chora", 2021, "Sree Vishnu", "Hasith Goli", "Crime/Comedy", "Cult favourite"],
  ["Tuck Jagadish", 2021, "Nani", "Shiva Nirvana", "Family/Drama", "Star vehicle"],
  ["Bangarraju", 2022, "Nagarjuna & Naga Chaitanya", "Kalyan Krishna Kurasala", "Fantasy/Comedy", "Star vehicle"],
  ["DJ Tillu", 2022, "Siddhu Jonnalagadda", "Vimal Krishna", "Crime/Comedy", "Breakout hit"],
  ["Bheemla Nayak", 2022, "Pawan Kalyan & Rana Daggubati", "Sagar K Chandra", "Action/Drama", "Star vehicle"],
  ["Ante Sundaraniki", 2022, "Nani", "Vivek Athreya", "Romance/Comedy", "Cult favourite"],
  ["Virata Parvam", 2022, "Rana Daggubati", "Venu Udugula", "Period/Drama", "Cult favourite"],
  ["Karthikeya 2", 2022, "Nikhil Siddhartha", "Chandoo Mondeti", "Adventure/Mystery", "Breakout hit"],
  ["Bimbisara", 2022, "Nandamuri Kalyan Ram", "Mallidi Vassishta", "Fantasy/Action", "Breakout hit"],
  ["Oke Oka Jeevitham", 2022, "Sharwanand", "Shree Karthick", "Sci-Fi/Drama", "Cult favourite"],
  ["GodFather", 2022, "Chiranjeevi", "Mohan Raja", "Political/Action", "Star vehicle"],
  ["Masooda", 2022, "Sangeetha", "Sai Kiran Daida", "Horror/Drama", "Cult favourite"],
  ["HIT: The Second Case", 2022, "Adivi Sesh", "Sailesh Kolanu", "Crime/Thriller", "Breakout hit"],
  ["Dhamaka", 2022, "Ravi Teja", "Trinadha Rao Nakkina", "Action/Comedy", "Star vehicle"],
  ["18 Pages", 2022, "Nikhil Siddhartha", "Palnati Surya Pratap", "Romance/Drama", "Breakout hit"],
  ["Radhe Shyam", 2022, "Prabhas", "Radha Krishna Kumar", "Romance/Drama", "Star vehicle"],
  ["Acharya", 2022, "Chiranjeevi & Ram Charan", "Koratala Siva", "Action/Drama", "Star vehicle"],
  ["Liger", 2022, "Vijay Deverakonda", "Puri Jagannadh", "Sports/Action", "Star vehicle"],
  ["The Ghost", 2022, "Nagarjuna", "Praveen Sattaru", "Action/Thriller", "Star vehicle"],
  ["Waltair Veerayya", 2023, "Chiranjeevi", "K. S. Ravindra", "Action/Comedy", "Star vehicle"],
  ["Veera Simha Reddy", 2023, "Nandamuri Balakrishna", "Gopichand Malineni", "Action/Drama", "Star vehicle"],
  ["Writer Padmabhushan", 2023, "Suhas", "Shanmukha Prasanth", "Comedy/Drama", "Breakout hit"],
  ["Sir", 2023, "Dhanush", "Venky Atluri", "Drama/Action", "Breakout hit"],
  ["Virupaksha", 2023, "Sai Dharam Tej", "Karthik Dandu", "Horror/Thriller", "Breakout hit"],
  ["Custody", 2023, "Naga Chaitanya", "Venkat Prabhu", "Action/Thriller", "Star vehicle"],
  ["Mem Famous", 2023, "Sumanth Prabhas", "Sumanth Prabhas", "Comedy/Drama", "Breakout hit"],
  ["Samajavaragamana", 2023, "Sree Vishnu", "Ram Abbaraju", "Comedy/Drama", "Breakout hit"],
  ["Baby", 2023, "Anand Deverakonda", "Sai Rajesh Neelam", "Romance/Drama", "Breakout hit"],
  ["Bro", 2023, "Pawan Kalyan & Sai Dharam Tej", "Samuthirakani", "Fantasy/Comedy", "Star vehicle"],
  ["Miss Shetty Mr Polishetty", 2023, "Anushka Shetty", "Mahesh Babu P.", "Romance/Comedy", "Breakout hit"],
  ["MAD", 2023, "Narne Nithin", "Kalyan Shankar", "Comedy/Drama", "Breakout hit"],
  ["Bhagavanth Kesari", 2023, "Nandamuri Balakrishna", "Anil Ravipudi", "Action/Drama", "Star vehicle"],
  ["Keedaa Cola", 2023, "Chaitanya Rao", "Tharun Bhascker", "Crime/Comedy", "Cult favourite"],
  ["Mangalavaaram", 2023, "Payal Rajput", "Ajay Bhupathi", "Mystery/Thriller", "Cult favourite"],
  ["Salaar: Part 1 – Ceasefire", 2023, "Prabhas", "Prashanth Neel", "Action/Drama", "Star vehicle"],
  ["Agent", 2023, "Akhil Akkineni", "Surender Reddy", "Spy/Action", "Star vehicle"],
  ["Adipurush", 2023, "Prabhas", "Om Raut", "Mythology/Action", "Star vehicle"],
  ["Bhola Shankar", 2023, "Chiranjeevi", "Meher Ramesh", "Action/Drama", "Star vehicle"],
  ["Skanda", 2023, "Ram Pothineni", "Boyapati Srinu", "Action/Drama", "Star vehicle"],
  ["Guntur Kaaram", 2024, "Mahesh Babu", "Trivikram Srinivas", "Action/Drama", "Star vehicle"],
  ["Saindhav", 2024, "Venkatesh", "Sailesh Kolanu", "Action/Drama", "Star vehicle"],
  ["Eagle", 2024, "Ravi Teja", "Karthik Gattamneni", "Action/Thriller", "Star vehicle"],
  ["Tillu Square", 2024, "Siddhu Jonnalagadda", "Mallik Ram", "Crime/Comedy", "Breakout hit"],
  ["The Family Star", 2024, "Vijay Deverakonda", "Parasuram", "Romance/Drama", "Star vehicle"],
  ["Gaami", 2024, "Vishwak Sen", "Vidyadhar Kagita", "Adventure/Drama", "Cult favourite"],
  ["Committee Kurrollu", 2024, "Sandeep Saroj", "Yadhu Vamsi", "Comedy/Drama", "Breakout hit"],
  ["Aay", 2024, "Narne Nithin", "Anji K. Maniputhra", "Romance/Comedy", "Breakout hit"],
  ["Saripodhaa Sanivaaram", 2024, "Nani", "Vivek Athreya", "Action/Drama", "Star vehicle"],
  ["Mathu Vadalara 2", 2024, "Sri Simha", "Ritesh Rana", "Crime/Comedy", "Breakout hit"],
  ["Devara: Part 1", 2024, "Jr NTR", "Koratala Siva", "Action/Drama", "Star vehicle"],
  ["KA", 2024, "Kiran Abbavaram", "Sujeeth & Sandeep", "Mystery/Thriller", "Breakout hit"],
  ["Pushpa 2: The Rule", 2024, "Allu Arjun", "Sukumar", "Action/Drama", "Star vehicle"],
  ["35 Chinna Katha Kaadu", 2024, "Nivetha Thomas", "Nanda Kishore Emani", "Family/Drama", "Cult favourite"],
  ["Game Changer", 2025, "Ram Charan", "S. Shankar", "Political/Action", "Star vehicle"],
  ["Daaku Maharaaj", 2025, "Nandamuri Balakrishna", "K. S. Ravindra", "Action/Drama", "Star vehicle"],
  ["Sankranthiki Vasthunam", 2025, "Venkatesh", "Anil Ravipudi", "Comedy/Drama", "Star vehicle"],
  ["Thandel", 2025, "Naga Chaitanya", "Chandoo Mondeti", "Romance/Drama", "Star vehicle"],
  ["Court: State vs A Nobody", 2025, "Priyadarshi", "Ram Jagadeesh", "Legal/Drama", "Breakout hit"],
  ["MAD Square", 2025, "Narne Nithin", "Kalyan Shankar", "Comedy/Drama", "Breakout hit"],
  ["HIT: The Third Case", 2025, "Nani", "Sailesh Kolanu", "Crime/Thriller", "Star vehicle"],
  ["Kuberaa", 2025, "Dhanush & Nagarjuna", "Sekhar Kammula", "Crime/Drama", "Star vehicle"],
  ["Hari Hara Veera Mallu", 2025, "Pawan Kalyan", "Jyothi Krishna", "Period/Action", "Star vehicle"],

  // Additional major-star filmography coverage
  ["Mrugaraju", 2001, "Chiranjeevi", "Gunasekhar", "Action/Adventure", "Star vehicle"],
  ["Sri Manjunatha", 2001, "Chiranjeevi", "K. Raghavendra Rao", "Devotional/Drama", "Star vehicle"],
  ["Anji", 2004, "Chiranjeevi", "Kodi Ramakrishna", "Fantasy/Adventure", "Star vehicle"],
  ["Jai Chiranjeeva", 2005, "Chiranjeevi", "K. Vijaya Bhaskar", "Action/Comedy", "Star vehicle"],
  ["Shankar Dada Zindabad", 2007, "Chiranjeevi", "Prabhu Deva", "Comedy/Drama", "Star vehicle"],
  ["Gudumba Shankar", 2004, "Pawan Kalyan", "Veera Shankar", "Action/Comedy", "Star vehicle"],
  ["Bangaram", 2006, "Pawan Kalyan", "Dharani", "Action/Drama", "Star vehicle"],
  ["Annavaram", 2006, "Pawan Kalyan", "Bhimaneni Srinivasa Rao", "Action/Drama", "Star vehicle"],
  ["Teen Maar", 2011, "Pawan Kalyan", "Jayanth C. Paranjee", "Romance/Drama", "Star vehicle"],
  ["Bobby", 2002, "Mahesh Babu", "Sobhan", "Romance/Drama", "Star vehicle"],
  ["Naani", 2004, "Mahesh Babu", "S. J. Suryah", "Fantasy/Comedy", "Star vehicle"],
  ["Sarkaru Vaari Paata", 2022, "Mahesh Babu", "Parasuram", "Action/Comedy", "Star vehicle"],
  ["Ninnu Choodalani", 2001, "Jr NTR", "V. R. Prathap", "Romance/Drama", "Star vehicle"],
  ["Subbu", 2001, "Jr NTR", "Rudraraju Suresh Varma", "Action/Romance", "Star vehicle"],
  ["Allari Ramudu", 2002, "Jr NTR", "B. Gopal", "Family/Drama", "Star vehicle"],
  ["Naaga", 2003, "Jr NTR", "D. K. Suresh", "Political/Action", "Star vehicle"],
  ["Samba", 2004, "Jr NTR", "V. V. Vinayak", "Action/Drama", "Star vehicle"],
  ["Naa Alludu", 2005, "Jr NTR", "Vara Mullapudi", "Comedy/Drama", "Star vehicle"],
  ["Narasimhudu", 2005, "Jr NTR", "B. Gopal", "Action/Drama", "Star vehicle"],
  ["Ashok", 2006, "Jr NTR", "Surender Reddy", "Action/Drama", "Star vehicle"],
  ["Dammu", 2012, "Jr NTR", "Boyapati Srinu", "Action/Drama", "Star vehicle"],
  ["Raghavendra", 2003, "Prabhas", "Suresh Krissna", "Action/Drama", "Star vehicle"],
  ["Adavi Ramudu", 2004, "Prabhas", "B. Gopal", "Action/Romance", "Star vehicle"],
  ["Chakram", 2005, "Prabhas", "Krishna Vamsi", "Drama/Romance", "Star vehicle"],
  ["Pournami", 2006, "Prabhas", "Prabhu Deva", "Romance/Drama", "Star vehicle"],
  ["Bunny", 2005, "Allu Arjun", "V. V. Vinayak", "Action/Drama", "Star vehicle"],
  ["Varudu", 2010, "Allu Arjun", "Gunasekhar", "Action/Romance", "Star vehicle"],
  ["Iddarammayilatho", 2013, "Allu Arjun", "Puri Jagannadh", "Action/Romance", "Star vehicle"],
  ["Sarrainodu", 2016, "Allu Arjun", "Boyapati Srinu", "Action/Drama", "Star vehicle"],
  ["Duvvada Jagannadham", 2017, "Allu Arjun", "Harish Shankar", "Action/Comedy", "Star vehicle"],
  ["Racha", 2012, "Ram Charan", "Sampath Nandi", "Action/Drama", "Star vehicle"],
  ["Toofan", 2013, "Ram Charan", "Apoorva Lakhia", "Action/Crime", "Star vehicle"],
  ["Govindudu Andarivadele", 2014, "Ram Charan", "Krishna Vamsi", "Family/Drama", "Star vehicle"],
  ["Eduruleni Manishi", 2001, "Nagarjuna", "Jonnalagadda Srinivasa Rao", "Action/Comedy", "Star vehicle"],
  ["Bava Nachadu", 2001, "Nagarjuna", "K. S. Ravikumar", "Romance/Drama", "Star vehicle"],
  ["Adhipathi", 2001, "Nagarjuna", "Ravi Raja Pinisetty", "Action/Drama", "Star vehicle"],
  ["Akasa Veedhilo", 2001, "Nagarjuna", "Singeetam Srinivasa Rao", "Romance/Drama", "Star vehicle"],
  ["Boss", 2006, "Nagarjuna", "V. N. Aditya", "Romance/Drama", "Star vehicle"],
  ["Don", 2007, "Nagarjuna", "Raghava Lawrence", "Action/Drama", "Star vehicle"],
  ["Kedi", 2010, "Nagarjuna", "Kiran Kumar", "Action/Thriller", "Star vehicle"],
  ["Ragada", 2010, "Nagarjuna", "Veeru Potla", "Action/Comedy", "Star vehicle"],
  ["Rajanna", 2011, "Nagarjuna", "V. Vijayendra Prasad", "Historical/Drama", "Star vehicle"],
  ["Bhai", 2013, "Nagarjuna", "Veerabhadram Chowdary", "Action/Comedy", "Star vehicle"],
  ["Om Namo Venkatesaya", 2017, "Nagarjuna", "K. Raghavendra Rao", "Devotional/Drama", "Star vehicle"],
  ["Raju Gari Gadhi 2", 2017, "Nagarjuna", "Ohmkar", "Horror/Comedy", "Star vehicle"],
  ["Officer", 2018, "Nagarjuna", "Ram Gopal Varma", "Action/Thriller", "Star vehicle"],
  ["Devadas", 2018, "Nagarjuna & Nani", "Sriram Adittya", "Action/Comedy", "Star vehicle"],
  ["Wild Dog", 2021, "Nagarjuna", "Ahishor Solomon", "Action/Thriller", "Star vehicle"],
  ["Naa Saami Ranga", 2024, "Nagarjuna", "Vijay Binni", "Action/Drama", "Star vehicle"],
  ["Devi Putrudu", 2001, "Venkatesh", "Kodi Ramakrishna", "Fantasy/Drama", "Star vehicle"],
  ["Prematho Raa", 2001, "Venkatesh", "Udayasankar", "Romance/Drama", "Star vehicle"],
  ["Subash Chandra Bose", 2005, "Venkatesh", "K. Raghavendra Rao", "Historical/Drama", "Star vehicle"],
  ["Lakshmi", 2006, "Venkatesh", "V. V. Vinayak", "Action/Drama", "Star vehicle"],
  ["Chintakayala Ravi", 2008, "Venkatesh", "Yogi", "Romance/Comedy", "Star vehicle"],
  ["Namo Venkatesa", 2010, "Venkatesh", "Srinu Vaitla", "Action/Comedy", "Star vehicle"],
  ["Nagavalli", 2010, "Venkatesh", "P. Vasu", "Horror/Drama", "Star vehicle"],
  ["Bodyguard", 2012, "Venkatesh", "Gopichand Malineni", "Action/Romance", "Star vehicle"],
  ["Masala", 2013, "Venkatesh & Ram Pothineni", "K. Vijaya Bhaskar", "Comedy/Drama", "Star vehicle"],
  ["Babu Bangaram", 2016, "Venkatesh", "Maruthi", "Action/Comedy", "Star vehicle"],
  ["Guru", 2017, "Venkatesh", "Sudha Kongara", "Sports/Drama", "Star vehicle"],
  ["Venky Mama", 2019, "Venkatesh & Naga Chaitanya", "K. S. Ravindra", "Action/Comedy", "Star vehicle"],
  ["Narappa", 2021, "Venkatesh", "Srikanth Addala", "Action/Drama", "Star vehicle"],
  ["Drushyam 2", 2021, "Venkatesh", "Jeethu Joseph", "Thriller/Drama", "Star vehicle"],
  ["F3: Fun and Frustration", 2022, "Venkatesh & Varun Tej", "Anil Ravipudi", "Comedy/Drama", "Star vehicle"],
  ["Vamsoddharakudu", 2000, "Nandamuri Balakrishna", "Sarath", "Action/Drama", "Star vehicle"],
  ["Goppinti Alludu", 2000, "Nandamuri Balakrishna", "E. V. V. Satyanarayana", "Comedy/Drama", "Star vehicle"],
  ["Bhalevadivi Basu", 2001, "Nandamuri Balakrishna", "P. A. Arun Prasad", "Action/Comedy", "Star vehicle"],
  ["Seema Simham", 2002, "Nandamuri Balakrishna", "G. Ram Prasad", "Action/Drama", "Star vehicle"],
  ["Chennakesava Reddy", 2002, "Nandamuri Balakrishna", "V. V. Vinayak", "Action/Drama", "Star vehicle"],
  ["Palnati Brahmanayudu", 2003, "Nandamuri Balakrishna", "B. Gopal", "Action/Drama", "Star vehicle"],
  ["Vijayendra Varma", 2004, "Nandamuri Balakrishna", "Swarna Subba Rao", "Action/Drama", "Star vehicle"],
  ["Allari Pidugu", 2005, "Nandamuri Balakrishna", "Jayanth C. Paranjee", "Action/Drama", "Star vehicle"],
  ["Veerabhadra", 2006, "Nandamuri Balakrishna", "A. S. Ravi Kumar Chowdary", "Action/Drama", "Star vehicle"],
  ["Maharadhi", 2007, "Nandamuri Balakrishna", "P. Vasu", "Action/Drama", "Star vehicle"],
  ["Okka Magadu", 2008, "Nandamuri Balakrishna", "Y. V. S. Chowdary", "Action/Drama", "Star vehicle"],
  ["Pandurangadu", 2008, "Nandamuri Balakrishna", "K. Raghavendra Rao", "Devotional/Drama", "Star vehicle"],
  ["Mitrudu", 2009, "Nandamuri Balakrishna", "A. Mahadev", "Romance/Drama", "Star vehicle"],
  ["Parama Veera Chakra", 2011, "Nandamuri Balakrishna", "Dasari Narayana Rao", "Action/Drama", "Star vehicle"],
  ["Adhinayakudu", 2012, "Nandamuri Balakrishna", "Paruchuri Murali", "Action/Drama", "Star vehicle"],
  ["Srimannarayana", 2012, "Nandamuri Balakrishna", "Ravi Chavali", "Action/Drama", "Star vehicle"],
  ["Lion", 2015, "Nandamuri Balakrishna", "Satyadev", "Action/Drama", "Star vehicle"],
  ["Dictator", 2016, "Nandamuri Balakrishna", "Sriwass", "Action/Drama", "Star vehicle"],
  ["Paisa Vasool", 2017, "Nandamuri Balakrishna", "Puri Jagannadh", "Action/Comedy", "Star vehicle"],
  ["Jai Simha", 2018, "Nandamuri Balakrishna", "K. S. Ravikumar", "Action/Drama", "Star vehicle"],
  ["NTR: Kathanayakudu", 2019, "Nandamuri Balakrishna", "Krish Jagarlamudi", "Biography/Drama", "Star vehicle"],
  ["Ruler", 2019, "Nandamuri Balakrishna", "K. S. Ravikumar", "Action/Drama", "Star vehicle"],
  ["Ride", 2009, "Nani", "Ramesh Varma", "Action/Drama", "Breakout hit"],
  ["Snehituda", 2009, "Nani", "Satyam Bellamkonda", "Romance/Drama", "Breakout hit"],
  ["Bheemili Kabaddi Jattu", 2010, "Nani", "Tatineni Satya", "Sports/Drama", "Breakout hit"],
  ["Paisa", 2014, "Nani", "Krishna Vamsi", "Crime/Drama", "Star vehicle"],
  ["Aaha Kalyanam", 2014, "Nani", "A. Gokul Krishna", "Romance/Comedy", "Star vehicle"],
  ["Janda Pai Kapiraju", 2015, "Nani", "Samuthirakani", "Action/Drama", "Star vehicle"],
  ["Majnu", 2016, "Nani", "Virinchi Varma", "Romance/Comedy", "Star vehicle"],
  ["Ninnu Kori", 2017, "Nani", "Shiva Nirvana", "Romance/Drama", "Star vehicle"],
  ["MCA", 2017, "Nani", "Venu Sriram", "Action/Comedy", "Star vehicle"],
  ["Krishnarjuna Yudham", 2018, "Nani", "Merlapaka Gandhi", "Action/Comedy", "Star vehicle"],
  ["Avunu Valliddaru Ista Paddaru!", 2002, "Ravi Teja", "Vamsy", "Romance/Comedy", "Breakout hit"],
  ["Naa Autograph", 2004, "Ravi Teja", "S. Gopal Reddy", "Romance/Drama", "Star vehicle"],
  ["Bhageeratha", 2005, "Ravi Teja", "Rasool Ellore", "Action/Drama", "Star vehicle"],
  ["Khatarnak", 2006, "Ravi Teja", "Amma Rajasekhar", "Action/Comedy", "Star vehicle"],
  ["Baladur", 2008, "Ravi Teja", "K. R. Udayasankar", "Action/Drama", "Star vehicle"],
  ["Anjaneyulu", 2009, "Ravi Teja", "Parasuram", "Action/Comedy", "Star vehicle"],
  ["Don Seenu", 2010, "Ravi Teja", "Gopichand Malineni", "Action/Comedy", "Star vehicle"],
  ["Mirapakay", 2011, "Ravi Teja", "Harish Shankar", "Action/Comedy", "Star vehicle"],
  ["Nippu", 2012, "Ravi Teja", "Gunasekhar", "Action/Drama", "Star vehicle"],
  ["Daruvu", 2012, "Ravi Teja", "Siva", "Fantasy/Comedy", "Star vehicle"],
  ["Power", 2014, "Ravi Teja", "K. S. Ravindra", "Action/Comedy", "Star vehicle"],
  ["Bengal Tiger", 2015, "Ravi Teja", "Sampath Nandi", "Action/Comedy", "Star vehicle"],
  ["Touch Chesi Chudu", 2018, "Ravi Teja", "Vikram Sirikonda", "Action/Comedy", "Star vehicle"],
  ["Disco Raja", 2020, "Ravi Teja", "Vi Anand", "Sci-Fi/Action", "Star vehicle"],
  ["Khiladi", 2022, "Ravi Teja", "Ramesh Varma", "Action/Thriller", "Star vehicle"],
  ["Ramarao on Duty", 2022, "Ravi Teja", "Sarath Mandava", "Action/Thriller", "Star vehicle"],
  ["Tiger Nageswara Rao", 2023, "Ravi Teja", "Vamsee", "Period/Action", "Star vehicle"],
  ["Mr. Bachchan", 2024, "Ravi Teja", "Harish Shankar", "Action/Drama", "Star vehicle"],

  // Complete mainstream filmography coverage for established lead actors
  ["Nuvvu Vastavani", 2000, "Nagarjuna", "V. R. Prathap", "Romance/Drama", "Star vehicle"],
  ["Ninne Premistha", 2000, "Nagarjuna", "R. R. Shinde", "Romance/Drama", "Star vehicle"],
  ["Snehamante Idera", 2001, "Nagarjuna", "Balasekaran", "Drama/Romance", "Star vehicle"],
  ["Nenunnanu", 2004, "Nagarjuna", "V. N. Aditya", "Romance/Drama", "Star vehicle"],
  ["Krishnarjuna", 2008, "Nagarjuna & Vishnu Manchu", "P. Vasu", "Fantasy/Comedy", "Star vehicle"],
  ["Gaganam", 2011, "Nagarjuna", "Radha Mohan", "Thriller/Drama", "Star vehicle"],
  ["Shirdi Sai", 2012, "Nagarjuna", "K. Raghavendra Rao", "Devotional/Drama", "Star vehicle"],
  ["Greeku Veerudu", 2013, "Nagarjuna", "Dasaradh", "Romance/Comedy", "Star vehicle"],
  ["Manmadhudu 2", 2019, "Nagarjuna", "Rahul Ravindran", "Romance/Comedy", "Star vehicle"],
  ["Eenadu", 2009, "Venkatesh", "Chakri Toleti", "Crime/Thriller", "Star vehicle"],
  ["NTR: Mahanayakudu", 2019, "Nandamuri Balakrishna", "Krish Jagarlamudi", "Biography/Drama", "Star vehicle"],
  ["They Call Him OG", 2025, "Pawan Kalyan", "Sujeeth", "Action/Crime", "Star vehicle"],
  ["Yeto Vellipoyindhi Manasu", 2012, "Nani", "Gautham Vasudev Menon", "Romance/Drama", "Star vehicle"],

  // Gopichand
  ["Tholi Valapu", 2001, "Gopichand", "Muthyala Subbaiah", "Romance/Drama", "Star vehicle"],
  ["Yagnam", 2004, "Gopichand", "A. S. Ravi Kumar Chowdary", "Action/Drama", "Star vehicle"],
  ["Andhrudu", 2005, "Gopichand", "Paruchuri Murali", "Action/Drama", "Star vehicle"],
  ["Ranam", 2006, "Gopichand", "Amma Rajasekhar", "Action/Comedy", "Star vehicle"],
  ["Raraju", 2006, "Gopichand", "Udayasankar", "Drama/Romance", "Star vehicle"],
  ["Okkadunnadu", 2007, "Gopichand", "Chandra Sekhar Yeleti", "Action/Thriller", "Star vehicle"],
  ["Lakshyam", 2007, "Gopichand", "Sriwass", "Action/Drama", "Star vehicle"],
  ["Ontari", 2008, "Gopichand", "B. V. Ramana", "Action/Drama", "Star vehicle"],
  ["Souryam", 2008, "Gopichand", "Siva", "Action/Drama", "Star vehicle"],
  ["Sankham", 2009, "Gopichand", "Siva", "Action/Drama", "Star vehicle"],
  ["Golimaar", 2010, "Gopichand", "Puri Jagannadh", "Action/Crime", "Star vehicle"],
  ["Wanted", 2011, "Gopichand", "B. V. S. Ravi", "Action/Drama", "Star vehicle"],
  ["Mogudu", 2011, "Gopichand", "Krishna Vamsi", "Family/Drama", "Star vehicle"],
  ["Sahasam", 2013, "Gopichand", "Chandra Sekhar Yeleti", "Adventure/Action", "Star vehicle"],
  ["Jil", 2015, "Gopichand", "Radha Krishna Kumar", "Action/Romance", "Star vehicle"],
  ["Soukhyam", 2015, "Gopichand", "A. S. Ravi Kumar Chowdary", "Action/Comedy", "Star vehicle"],
  ["Goutham Nanda", 2017, "Gopichand", "Sampath Nandi", "Action/Drama", "Star vehicle"],
  ["Oxygen", 2017, "Gopichand", "A. M. Jyothi Krishna", "Action/Thriller", "Star vehicle"],
  ["Pantham", 2018, "Gopichand", "K. Chakravarthy Reddy", "Action/Drama", "Star vehicle"],
  ["Chanakya", 2019, "Gopichand", "Thiru", "Spy/Thriller", "Star vehicle"],
  ["Seetimaarr", 2021, "Gopichand", "Sampath Nandi", "Sports/Action", "Star vehicle"],
  ["Aaradugula Bullet", 2021, "Gopichand", "B. Gopal", "Action/Drama", "Star vehicle"],
  ["Pakka Commercial", 2022, "Gopichand", "Maruthi", "Action/Comedy", "Star vehicle"],
  ["Ramabanam", 2023, "Gopichand", "Sriwass", "Action/Drama", "Star vehicle"],
  ["Bhimaa", 2024, "Gopichand", "A. Harsha", "Action/Fantasy", "Star vehicle"],
  ["Viswam", 2024, "Gopichand", "Srinu Vaitla", "Action/Comedy", "Star vehicle"],

  // Nithiin
  ["Sambaram", 2003, "Nithiin", "Dasaradh", "Romance/Drama", "Star vehicle"],
  ["Sri Anjaneyam", 2004, "Nithiin", "Krishna Vamsi", "Fantasy/Action", "Star vehicle"],
  ["Sye", 2004, "Nithiin", "S. S. Rajamouli", "Sports/Action", "Star vehicle"],
  ["Dhairyam", 2005, "Nithiin", "Teja", "Action/Romance", "Star vehicle"],
  ["Allari Bullodu", 2005, "Nithiin", "K. Raghavendra Rao", "Comedy/Romance", "Star vehicle"],
  ["Raam", 2006, "Nithiin", "N. Shankar", "Action/Drama", "Star vehicle"],
  ["Takkari", 2007, "Nithiin", "Amma Rajasekhar", "Action/Comedy", "Star vehicle"],
  ["Aatadista", 2008, "Nithiin", "A. S. Ravi Kumar Chowdary", "Action/Romance", "Star vehicle"],
  ["Victory", 2008, "Nithiin", "Ravi C. Kumar", "Action/Drama", "Star vehicle"],
  ["Drona", 2009, "Nithiin", "J. Karun Kumar", "Action/Drama", "Star vehicle"],
  ["Rechipo", 2009, "Nithiin", "Paruchuri Murali", "Action/Romance", "Star vehicle"],
  ["Seetharamula Kalyanam", 2010, "Nithiin", "Eeshwar", "Action/Romance", "Star vehicle"],
  ["Maaro", 2011, "Nithiin", "Siddique", "Action/Comedy", "Star vehicle"],
  ["Chinnadana Nee Kosam", 2014, "Nithiin", "A. Karunakaran", "Romance/Comedy", "Star vehicle"],
  ["Courier Boy Kalyan", 2015, "Nithiin", "Premsai", "Action/Romance", "Star vehicle"],
  ["LIE", 2017, "Nithiin", "Hanu Raghavapudi", "Action/Thriller", "Star vehicle"],
  ["Chal Mohan Ranga", 2018, "Nithiin", "Krishna Chaitanya", "Romance/Comedy", "Star vehicle"],
  ["Srinivasa Kalyanam", 2018, "Nithiin", "Satish Vegesna", "Family/Romance", "Star vehicle"],
  ["Rang De", 2021, "Nithiin", "Venky Atluri", "Romance/Comedy", "Star vehicle"],
  ["Maestro", 2021, "Nithiin", "Merlapaka Gandhi", "Crime/Thriller", "Star vehicle"],
  ["Macherla Niyojakavargam", 2022, "Nithiin", "M. S. Rajashekhar Reddy", "Political/Action", "Star vehicle"],
  ["Extra Ordinary Man", 2023, "Nithiin", "Vakkantham Vamsi", "Action/Comedy", "Star vehicle"],
  ["Robinhood", 2025, "Nithiin", "Venky Kudumula", "Action/Comedy", "Star vehicle"],
  ["Thammudu", 2025, "Nithiin", "Venu Sriram", "Action/Drama", "Star vehicle"],

  // Ram Pothineni
  ["Jagadam", 2007, "Ram Pothineni", "Sukumar", "Action/Drama", "Star vehicle"],
  ["Maska", 2009, "Ram Pothineni", "B. Gopal", "Action/Romance", "Star vehicle"],
  ["Ganesh", 2009, "Ram Pothineni", "M. Saravanan", "Romance/Comedy", "Star vehicle"],
  ["Rama Rama Krishna Krishna", 2010, "Ram Pothineni", "Srinivas", "Action/Comedy", "Star vehicle"],
  ["Endukante Premanta", 2012, "Ram Pothineni", "A. Karunakaran", "Fantasy/Romance", "Star vehicle"],
  ["Ongole Githa", 2013, "Ram Pothineni", "Bhaskar", "Action/Drama", "Star vehicle"],
  ["Pandaga Chesko", 2015, "Ram Pothineni", "Gopichand Malineni", "Action/Comedy", "Star vehicle"],
  ["Shivam", 2015, "Ram Pothineni", "Sreenivasa Reddy", "Action/Romance", "Star vehicle"],
  ["Nenu Sailaja", 2016, "Ram Pothineni", "Kishore Tirumala", "Romance/Comedy", "Star vehicle"],
  ["Hyper", 2016, "Ram Pothineni", "Santosh Srinivas", "Action/Comedy", "Star vehicle"],
  ["Vunnadhi Okate Zindagi", 2017, "Ram Pothineni", "Kishore Tirumala", "Drama/Romance", "Star vehicle"],
  ["Hello Guru Prema Kosame", 2018, "Ram Pothineni", "Trinadha Rao Nakkina", "Romance/Comedy", "Star vehicle"],
  ["iSmart Shankar", 2019, "Ram Pothineni", "Puri Jagannadh", "Sci-Fi/Action", "Star vehicle"],
  ["Red", 2021, "Ram Pothineni", "Kishore Tirumala", "Crime/Thriller", "Star vehicle"],
  ["The Warriorr", 2022, "Ram Pothineni", "N. Lingusamy", "Action/Drama", "Star vehicle"],
  ["Double iSmart", 2024, "Ram Pothineni", "Puri Jagannadh", "Sci-Fi/Action", "Star vehicle"],
  ["Andhra King Taluka", 2025, "Ram Pothineni", "Mahesh Babu P.", "Drama/Romance", "Star vehicle"],

  // Naga Chaitanya
  ["Dhada", 2011, "Naga Chaitanya", "Ajay Bhuyan", "Action/Romance", "Star vehicle"],
  ["Bejawada", 2011, "Naga Chaitanya", "Vivek Krishna", "Crime/Action", "Star vehicle"],
  ["Tadakha", 2013, "Naga Chaitanya", "Kishore Kumar Pardasani", "Action/Drama", "Star vehicle"],
  ["Autonagar Surya", 2014, "Naga Chaitanya", "Deva Katta", "Political/Action", "Star vehicle"],
  ["Oka Laila Kosam", 2014, "Naga Chaitanya", "Vijay Kumar Konda", "Romance/Comedy", "Star vehicle"],
  ["Dohchay", 2015, "Naga Chaitanya", "Sudheer Varma", "Crime/Comedy", "Star vehicle"],
  ["Premam", 2016, "Naga Chaitanya", "Chandoo Mondeti", "Romance/Drama", "Star vehicle"],
  ["Sahasam Swasaga Sagipo", 2016, "Naga Chaitanya", "Gautham Vasudev Menon", "Romance/Thriller", "Star vehicle"],
  ["Rarandoi Veduka Chudham", 2017, "Naga Chaitanya", "Kalyan Krishna Kurasala", "Family/Romance", "Star vehicle"],
  ["Yuddham Sharanam", 2017, "Naga Chaitanya", "Krishna Marimuthu", "Action/Thriller", "Star vehicle"],
  ["Savyasachi", 2018, "Naga Chaitanya", "Chandoo Mondeti", "Action/Thriller", "Star vehicle"],
  ["Shailaja Reddy Alludu", 2018, "Naga Chaitanya", "Maruthi", "Romance/Comedy", "Star vehicle"],
  ["Thank You", 2022, "Naga Chaitanya", "Vikram Kumar", "Drama/Romance", "Star vehicle"],

  // Nandamuri Kalyan Ram
  ["Abhimanyu", 2003, "Nandamuri Kalyan Ram", "A. Mallikarjun", "Action/Drama", "Star vehicle"],
  ["Athanokkade", 2005, "Nandamuri Kalyan Ram", "Surender Reddy", "Action/Drama", "Star vehicle"],
  ["Asadhyudu", 2006, "Nandamuri Kalyan Ram", "Anil Krishna", "Action/Drama", "Star vehicle"],
  ["Vijayadasami", 2007, "Nandamuri Kalyan Ram", "V. Samudra", "Action/Drama", "Star vehicle"],
  ["Hare Ram", 2008, "Nandamuri Kalyan Ram", "Harshavardhan", "Action/Thriller", "Star vehicle"],
  ["Jayeebhava", 2009, "Nandamuri Kalyan Ram", "Naren Kondapati", "Romance/Comedy", "Star vehicle"],
  ["Kalyanram Kathi", 2010, "Nandamuri Kalyan Ram", "A. Mallikarjun", "Action/Drama", "Star vehicle"],
  ["Om 3D", 2013, "Nandamuri Kalyan Ram", "Sunil Reddy", "Action/Thriller", "Star vehicle"],
  ["Pataas", 2015, "Nandamuri Kalyan Ram", "Anil Ravipudi", "Action/Comedy", "Star vehicle"],
  ["Sher", 2015, "Nandamuri Kalyan Ram", "A. Mallikarjun", "Action/Comedy", "Star vehicle"],
  ["Ism", 2016, "Nandamuri Kalyan Ram", "Puri Jagannadh", "Action/Drama", "Star vehicle"],
  ["MLA", 2018, "Nandamuri Kalyan Ram", "Upendra Madhav", "Action/Comedy", "Star vehicle"],
  ["Naa Nuvve", 2018, "Nandamuri Kalyan Ram", "Jayendra Panchapakesan", "Romance/Drama", "Star vehicle"],
  ["118", 2019, "Nandamuri Kalyan Ram", "K. V. Guhan", "Mystery/Thriller", "Star vehicle"],
  ["Entha Manchivaadavuraa", 2020, "Nandamuri Kalyan Ram", "Satish Vegesna", "Family/Drama", "Star vehicle"],
  ["Amigos", 2023, "Nandamuri Kalyan Ram", "Rajendra Reddy", "Action/Thriller", "Star vehicle"],
  ["Devil: The British Secret Agent", 2023, "Nandamuri Kalyan Ram", "Abhishek Nama", "Period/Action", "Star vehicle"],
  ["Arjun S/O Vyjayanthi", 2025, "Nandamuri Kalyan Ram", "Pradeep Chilukuri", "Action/Drama", "Star vehicle"],

  // Sai Dharam Tej and Varun Tej
  ["Pilla Nuvvu Leni Jeevitham", 2014, "Sai Dharam Tej", "A. S. Ravi Kumar Chowdary", "Action/Romance", "Star vehicle"],
  ["Rey", 2015, "Sai Dharam Tej", "Y. V. S. Chowdary", "Action/Musical", "Star vehicle"],
  ["Subramanyam for Sale", 2015, "Sai Dharam Tej", "Harish Shankar", "Action/Comedy", "Star vehicle"],
  ["Thikka", 2016, "Sai Dharam Tej", "Sunil Reddy", "Action/Comedy", "Star vehicle"],
  ["Winner", 2017, "Sai Dharam Tej", "Gopichand Malineni", "Action/Comedy", "Star vehicle"],
  ["Jawaan", 2017, "Sai Dharam Tej", "B. V. S. Ravi", "Action/Thriller", "Star vehicle"],
  ["Inttelligent", 2018, "Sai Dharam Tej", "V. V. Vinayak", "Action/Drama", "Star vehicle"],
  ["Tej I Love You", 2018, "Sai Dharam Tej", "A. Karunakaran", "Romance/Drama", "Star vehicle"],
  ["Solo Brathuke So Better", 2020, "Sai Dharam Tej", "Subbu", "Romance/Comedy", "Star vehicle"],
  ["Mukunda", 2014, "Varun Tej", "Srikanth Addala", "Drama/Romance", "Star vehicle"],
  ["Loafer", 2015, "Varun Tej", "Puri Jagannadh", "Action/Drama", "Star vehicle"],
  ["Mister", 2017, "Varun Tej", "Srinu Vaitla", "Romance/Comedy", "Star vehicle"],
  ["Antariksham 9000 KMPH", 2018, "Varun Tej", "Sankalp Reddy", "Sci-Fi/Thriller", "Star vehicle"],
  ["Gaddalakonda Ganesh", 2019, "Varun Tej", "Harish Shankar", "Action/Crime", "Star vehicle"],
  ["Ghani", 2022, "Varun Tej", "Kiran Korrapati", "Sports/Drama", "Star vehicle"],
  ["Gandeevadhari Arjuna", 2023, "Varun Tej", "Praveen Sattaru", "Action/Thriller", "Star vehicle"],
  ["Operation Valentine", 2024, "Varun Tej", "Shakti Pratap Singh", "Action/Drama", "Star vehicle"],
  ["Matka", 2024, "Varun Tej", "Karuna Kumar", "Period/Crime", "Star vehicle"],

  // Sharwanand
  ["Amma Cheppindi", 2006, "Sharwanand", "Gangaraju Gunnam", "Family/Drama", "Breakout hit"],
  ["Andari Bandhuvaya", 2010, "Sharwanand", "Chandra Siddhartha", "Drama/Family", "Star vehicle"],
  ["Ko Antey Koti", 2012, "Sharwanand", "Anish Kuruvilla", "Crime/Drama", "Star vehicle"],
  ["Express Raja", 2016, "Sharwanand", "Merlapaka Gandhi", "Comedy/Romance", "Star vehicle"],
  ["Radha", 2017, "Sharwanand", "Chandra Mohan", "Action/Comedy", "Star vehicle"],
  ["Padi Padi Leche Manasu", 2018, "Sharwanand", "Hanu Raghavapudi", "Romance/Drama", "Star vehicle"],
  ["Ranarangam", 2019, "Sharwanand", "Sudheer Varma", "Crime/Action", "Star vehicle"],
  ["Jaanu", 2020, "Sharwanand", "C. Prem Kumar", "Romance/Drama", "Star vehicle"],
  ["Sreekaram", 2021, "Sharwanand", "Kishor B.", "Drama/Family", "Star vehicle"],
  ["Maha Samudram", 2021, "Sharwanand", "Ajay Bhupathi", "Action/Drama", "Star vehicle"],
  ["Aadavallu Meeku Johaarlu", 2022, "Sharwanand", "Kishore Tirumala", "Family/Comedy", "Star vehicle"],
  ["Manamey", 2024, "Sharwanand", "Sriram Adittya", "Family/Comedy", "Star vehicle"],

  // Other major contemporary leads
  ["Dwaraka", 2017, "Vijay Deverakonda", "Srinivasa Ravindra", "Romance/Comedy", "Star vehicle"],
  ["NOTA", 2018, "Vijay Deverakonda", "Anand Shankar", "Political/Thriller", "Star vehicle"],
  ["Kushi", 2023, "Vijay Deverakonda", "Shiva Nirvana", "Romance/Drama", "Star vehicle"],
  ["Kingdom", 2025, "Vijay Deverakonda", "Gowtam Tinnanuri", "Spy/Action", "Star vehicle"],
  ["Surya vs Surya", 2015, "Nikhil Siddhartha", "Karthik Ghattamaneni", "Romance/Drama", "Breakout hit"],
  ["Keshava", 2017, "Nikhil Siddhartha", "Sudheer Varma", "Crime/Thriller", "Star vehicle"],
  ["Kirrak Party", 2018, "Nikhil Siddhartha", "Sharan Koppisetty", "Coming-of-age/Comedy", "Star vehicle"],
  ["Arjun Suravaram", 2019, "Nikhil Siddhartha", "T. N. Santhosh", "Crime/Thriller", "Star vehicle"],
  ["SPY", 2023, "Nikhil Siddhartha", "Garry BH", "Spy/Action", "Star vehicle"],
  ["Appudo Ippudo Eppudo", 2024, "Nikhil Siddhartha", "Sudheer Varma", "Romance/Thriller", "Star vehicle"],
  ["Ami Thumi", 2017, "Adivi Sesh", "Mohana Krishna Indraganti", "Comedy/Romance", "Breakout hit"],
  ["Falaknuma Das", 2019, "Vishwak Sen", "Vishwak Sen", "Crime/Drama", "Breakout hit"],
  ["Paagal", 2021, "Vishwak Sen", "Naresh Kuppili", "Romance/Comedy", "Star vehicle"],
  ["Ashoka Vanamlo Arjuna Kalyanam", 2022, "Vishwak Sen", "Vidya Sagar Chinta", "Romance/Comedy", "Breakout hit"],
  ["Ori Devuda", 2022, "Vishwak Sen", "Ashwath Marimuthu", "Fantasy/Romance", "Star vehicle"],
  ["Das Ka Dhamki", 2023, "Vishwak Sen", "Vishwak Sen", "Action/Comedy", "Star vehicle"],
  ["Gangs of Godavari", 2024, "Vishwak Sen", "Krishna Chaitanya", "Period/Action", "Star vehicle"],
  ["Mechanic Rocky", 2024, "Vishwak Sen", "Ravi Teja Mullapudi", "Action/Comedy", "Star vehicle"],
  ["Laila", 2025, "Vishwak Sen", "Ram Narayan", "Comedy/Action", "Star vehicle"],
  ["Sridevi Soda Center", 2021, "Sudheer Babu", "Karuna Kumar", "Action/Romance", "Star vehicle"],
  ["Aa Ammayi Gurinchi Meeku Cheppali", 2022, "Sudheer Babu", "Mohana Krishna Indraganti", "Romance/Drama", "Star vehicle"],
  ["Hunt", 2023, "Sudheer Babu", "Mahesh Surapaneni", "Action/Thriller", "Star vehicle"],
  ["Harom Hara", 2024, "Sudheer Babu", "Gnanasagar Dwaraka", "Period/Action", "Star vehicle"],
  ["Ee Abbai Chala Manchodu", 2003, "Ravi Teja", "Agathiyan", "Romance/Comedy", "Star vehicle"],
  ["Oka Raju Oka Rani", 2003, "Ravi Teja", "Yogi", "Romance/Comedy", "Star vehicle"],
  ["Dongodu", 2003, "Ravi Teja", "Bhimaneni Srinivasa Rao", "Comedy/Crime", "Star vehicle"],
  ["Veede", 2003, "Ravi Teja", "Ravi Raja Pinisetty", "Action/Drama", "Star vehicle"],
  ["Chanti", 2004, "Ravi Teja", "Sobhan", "Drama/Romance", "Star vehicle"],
  ["Shock", 2006, "Ravi Teja", "Harish Shankar", "Action/Thriller", "Star vehicle"],
  ["Neninthe", 2008, "Ravi Teja", "Puri Jagannadh", "Drama/Action", "Star vehicle"],
  ["Sambho Siva Sambho", 2010, "Ravi Teja", "Samuthirakani", "Action/Drama", "Star vehicle"],
  ["Dongala Mutha", 2011, "Ravi Teja", "Ram Gopal Varma", "Crime/Thriller", "Star vehicle"],
  ["Veera", 2011, "Ravi Teja", "Ramesh Varma", "Action/Drama", "Star vehicle"],
  ["Devudu Chesina Manushulu", 2012, "Ravi Teja", "Puri Jagannadh", "Fantasy/Comedy", "Star vehicle"],
  ["Sarocharu", 2012, "Ravi Teja", "Parasuram", "Romance/Drama", "Star vehicle"],
  ["Kick 2", 2015, "Ravi Teja", "Surender Reddy", "Action/Comedy", "Star vehicle"],
  ["Nela Ticket", 2018, "Ravi Teja", "Kalyan Krishna Kurasala", "Action/Drama", "Star vehicle"],
  ["Amar Akbar Anthony", 2018, "Ravi Teja", "Srinu Vaitla", "Action/Comedy", "Star vehicle"],
  ["Ravanasura", 2023, "Ravi Teja", "Sudheer Varma", "Crime/Thriller", "Star vehicle"],
  ["Mass Jathara", 2025, "Ravi Teja", "Bhanu Bogavarapu", "Action/Comedy", "Star vehicle"],
  ["Mirai", 2025, "Teja Sajja", "Karthik Gattamneni", "Fantasy/Adventure", "Star vehicle"],
  ["Akhanda 2: Thaandavam", 2025, "Nandamuri Balakrishna", "Boyapati Srinu", "Fantasy/Action", "Star vehicle"],

  // Breakout hits, sleeper successes, comedy favourites, and modern cult films
  ["Devullu", 2000, "Prithvi", "Kodi Ramakrishna", "Devotional/Drama", "Breakout hit"],
  ["Kshemanga Velli Labhamga Randi", 2000, "Srikanth", "Raja Vannem Reddy", "Comedy/Family", "Breakout hit"],
  ["Chirunavvutho", 2000, "Venu Thottempudi", "G. Ram Prasad", "Romance/Comedy", "Breakout hit"],
  ["Priyamaina Neeku", 2001, "Tarun", "Balasekaran", "Romance/Drama", "Breakout hit"],
  ["Hanuman Junction", 2001, "Arjun & Jagapathi Babu", "M. Raja", "Action/Comedy", "Breakout hit"],
  ["Allari", 2002, "Allari Naresh", "Ravi Babu", "Comedy/Romance", "Breakout hit"],
  ["Nuvve Nuvve", 2002, "Tarun", "Trivikram Srinivas", "Romance/Comedy", "Breakout hit"],
  ["Aaduthu Paaduthu", 2002, "Srikanth", "Devi Prasad", "Comedy/Romance", "Breakout hit"],
  ["Kabaddi Kabaddi", 2003, "Jagapathi Babu", "Venky", "Comedy/Romance", "Breakout hit"],
  ["Vennela", 2005, "Raja", "Deva Katta", "Romance/Comedy", "Cult favourite"],
  ["Kithakithalu", 2006, "Allari Naresh", "E. V. V. Satyanarayana", "Comedy/Romance", "Breakout hit"],
  ["Chandamama", 2007, "Navdeep", "Krishna Vamsi", "Family/Romance", "Breakout hit"],
  ["Anasuya", 2007, "Bhumika Chawla", "Ravi Babu", "Crime/Thriller", "Breakout hit"],
  ["Evadaithe Nakenti", 2007, "Rajasekhar", "V. Samudra", "Political/Action", "Breakout hit"],
  ["Avakai Biryani", 2008, "Kamal Kamaraju", "Anish Kuruvilla", "Romance/Drama", "Cult favourite"],
  ["Vinayakudu", 2008, "Krishnudu", "Sai Kiran Adivi", "Romance/Comedy", "Breakout hit"],
  ["Blade Babji", 2008, "Allari Naresh", "Devi Prasad", "Crime/Comedy", "Breakout hit"],
  ["Village Lo Vinayakudu", 2009, "Krishnudu", "Sai Kiran Adivi", "Romance/Comedy", "Breakout hit"],
  ["Betting Bangaraju", 2010, "Allari Naresh", "E. Satti Babu", "Comedy/Romance", "Breakout hit"],
  ["Golconda High School", 2011, "Sumanth", "Mohana Krishna Indraganti", "Sports/Drama", "Cult favourite"],
  ["Solo", 2011, "Nara Rohit", "Parasuram", "Romance/Drama", "Breakout hit"],
  ["Seema Tapakai", 2011, "Allari Naresh", "G. Nageswara Reddy", "Comedy/Romance", "Breakout hit"],
  ["Aha Naa Pellanta!", 2011, "Allari Naresh", "Veerabhadram Chowdary", "Comedy/Romance", "Breakout hit"],
  ["Ee Rojullo", 2012, "Srinivas", "Maruthi", "Romance/Comedy", "Breakout hit"],
  ["Andala Rakshasi", 2012, "Rahul Ravindran", "Hanu Raghavapudi", "Romance/Drama", "Cult favourite"],
  ["Avunu", 2012, "Poorna", "Ravi Babu", "Horror/Thriller", "Breakout hit"],
  ["Sudigadu", 2012, "Allari Naresh", "Bhimaneni Srinivasa Rao", "Comedy/Spoof", "Breakout hit"],
  ["Poola Rangadu", 2012, "Sunil", "Veerabhadram Chowdary", "Action/Comedy", "Breakout hit"],
  ["Mem Vayasuku Vacham", 2012, "Tanish", "Trinadha Rao Nakkina", "Romance/Drama", "Breakout hit"],
  ["Potugadu", 2013, "Manchu Manoj", "Pavan Wadeyar", "Romance/Comedy", "Breakout hit"],
  ["Ala Ela", 2014, "Rahul Ravindran", "Anish R. Krishna", "Romance/Comedy", "Breakout hit"],
  ["Geethanjali", 2014, "Anjali", "Raj Kiran", "Horror/Comedy", "Breakout hit"],
  ["Dikkulu Choodaku Ramayya", 2014, "Naga Shaurya", "Trikoti", "Romance/Comedy", "Breakout hit"],
  ["Cinema Choopistha Mava", 2015, "Raj Tarun", "Trinadha Rao Nakkina", "Romance/Comedy", "Breakout hit"],
  ["Bhale Manchi Roju", 2015, "Sudheer Babu", "Sriram Adittya", "Crime/Comedy", "Breakout hit"],
  ["Raju Gari Gadhi", 2015, "Ashwin Babu", "Ohmkar", "Horror/Comedy", "Breakout hit"],
  ["Kerintha", 2015, "Sumanth Ashwin", "Sai Kiran Adivi", "Coming-of-age/Drama", "Breakout hit"],
  ["Jyo Achyutananda", 2016, "Nara Rohit & Naga Shaurya", "Srinivas Avasarala", "Romance/Comedy", "Breakout hit"],
  ["Kalyana Vaibhogame", 2016, "Naga Shaurya", "Nandini Reddy", "Romance/Comedy", "Breakout hit"],
  ["Srirastu Subhamastu", 2016, "Allu Sirish", "Parasuram", "Romance/Family", "Breakout hit"],
  ["Mental Madhilo", 2017, "Sree Vishnu", "Vivek Athreya", "Romance/Comedy", "Breakout hit"],
  ["Anando Brahma", 2017, "Taapsee Pannu", "Mahi V. Raghav", "Horror/Comedy", "Breakout hit"],
  ["PSV Garuda Vega", 2017, "Rajasekhar", "Praveen Sattaru", "Spy/Thriller", "Breakout hit"],
  ["Chi La Sow", 2018, "Sushanth", "Rahul Ravindran", "Romance/Comedy", "Breakout hit"],
  ["Hushaaru", 2018, "Tejus Kancherla", "Sree Harsha Konuganti", "Coming-of-age/Comedy", "Breakout hit"],
  ["Sammohanam", 2018, "Sudheer Babu", "Mohana Krishna Indraganti", "Romance/Drama", "Breakout hit"],
  ["Mallesham", 2019, "Priyadarshi", "Raj R.", "Biography/Drama", "Cult favourite"],
  ["George Reddy", 2019, "Sandeep Madhav", "B. Jeevan Reddy", "Biography/Action", "Breakout hit"],
  ["Raja Vaaru Rani Gaaru", 2019, "Kiran Abbavaram", "Ravi Kiran Kola", "Romance/Drama", "Breakout hit"],
  ["SR Kalyanamandapam", 2021, "Kiran Abbavaram", "Sridhar Gade", "Romance/Drama", "Breakout hit"],
  ["Ek Mini Katha", 2021, "Santosh Sobhan", "Karthik Rapolu", "Comedy/Drama", "Breakout hit"],
  ["Vivaha Bhojanambu", 2021, "Satya", "Ram Abbaraju", "Comedy/Drama", "Breakout hit"],
  ["Adbhutham", 2021, "Teja Sajja", "Mallik Ram", "Sci-Fi/Romance", "Breakout hit"],
  ["Pushpaka Vimanam", 2021, "Anand Deverakonda", "Damodara", "Comedy/Thriller", "Cult favourite"],
  ["Urvasivo Rakshasivo", 2022, "Allu Sirish", "Rakesh Sashii", "Romance/Comedy", "Breakout hit"],
  ["Swathi Muthyam", 2022, "Bellamkonda Ganesh", "Lakshman K. Krishna", "Romance/Comedy", "Breakout hit"],
  ["Bedurulanka 2012", 2023, "Kartikeya Gummakonda", "Clax", "Comedy/Drama", "Breakout hit"],
  ["Maa Oori Polimera 2", 2023, "Satyam Rajesh", "Anil Viswanath", "Horror/Thriller", "Breakout hit"],
  ["Ambajipeta Marriage Band", 2024, "Suhas", "Dushyanth Katikaneni", "Drama/Romance", "Breakout hit"],
  ["Prasanna Vadanam", 2024, "Suhas", "Arjun Y. K.", "Crime/Thriller", "Breakout hit"],
  ["Maruthi Nagar Subramanyam", 2024, "Rao Ramesh", "Lakshman Karya", "Comedy/Drama", "Breakout hit"],
  ["Janaka Aithe Ganaka", 2024, "Suhas", "Sandeep Reddy Bandla", "Comedy/Drama", "Breakout hit"],
  ["Zebra", 2024, "Satyadev", "Eashvar Karthic", "Crime/Thriller", "Breakout hit"],
  ["Little Hearts", 2025, "Mouli Tanuj Prasanth", "Sai Marthand", "Romance/Comedy", "Breakout hit"],
  ["Raju Weds Rambai", 2025, "Akhil Uddemari", "Saailu Kampati", "Romance/Drama", "Breakout hit"],
  ["The Girlfriend", 2025, "Rashmika Mandanna", "Rahul Ravindran", "Romance/Drama", "Breakout hit"],
  ["K-Ramp", 2025, "Kiran Abbavaram", "Jains Nani", "Romance/Comedy", "Breakout hit"],
  ["Subham", 2025, "Harshith Reddy", "Praveen Kandregula", "Horror/Comedy", "Breakout hit"],
  ["Single", 2025, "Sree Vishnu", "Caarthick Raju", "Romance/Comedy", "Breakout hit"],
  ["Beauty", 2025, "Ankith Koyya", "JSS Vardhan", "Romance/Drama", "Breakout hit"],
  ["Dhandoraa", 2025, "Shivaji", "Murali Kanth", "Social/Drama", "Breakout hit"],

  // Released Telugu films from 2026 (through August 18)
  ["The RajaSaab", 2026, "Prabhas", "Maruthi", "Horror/Comedy", "Star vehicle"],
  ["Mana Shankara Vara Prasad Garu", 2026, "Chiranjeevi & Venkatesh", "Anil Ravipudi", "Action/Comedy", "Star vehicle"],
  ["Bhartha Mahasayulaku Wignyapthi", 2026, "Ravi Teja", "Kishore Tirumala", "Comedy/Drama", "Star vehicle"],
  ["Anaganaga Oka Raju", 2026, "Naveen Polishetty", "Maari", "Comedy/Romance", "Breakout hit"],
  ["Nari Nari Naduma Murari", 2026, "Sharwanand", "Ram Abbaraju", "Romance/Comedy", "Breakout hit"],
  ["Funky", 2026, "Vishwak Sen", "K. V. Anudeep", "Comedy/Drama", "Star vehicle"],
  ["Couple Friendly", 2026, "Santosh Sobhan", "Ashwin Chandrasekar", "Romance/Drama", "Breakout hit"],
  ["Hey Balwanth", 2026, "Suhas", "Gopi Atchara", "Comedy/Drama", "Breakout hit"],
  ["Vishnu Vinyasam", 2026, "Sree Vishnu", "Yadunaath Maruthi Rao", "Comedy/Drama", "Breakout hit"],
  ["Mrithyunjay", 2026, "Sree Vishnu", "Hussain Sha Kiran", "Mystery/Thriller", "Breakout hit"],
  ["Ustaad Bhagat Singh", 2026, "Pawan Kalyan", "Harish Shankar", "Action/Drama", "Star vehicle"],
  ["Suyodhana", 2026, "Priyadarshi", "Y. S. Madav Reddy", "Drama/Thriller", "Breakout hit"],
  ["Biker", 2026, "Sharwanand", "Abhilash Reddy", "Sports/Drama", "Star vehicle"],
  ["Raakaasa", 2026, "Sangeeth Sobhan", "Manasa Sharma", "Comedy/Drama", "Breakout hit"],
  ["Dacoit: A Love Story", 2026, "Adivi Sesh", "Shaneil Deo", "Action/Romance", "Star vehicle"],
  ["Bad Boy Karthik", 2026, "Naga Shaurya", "Ramesh Desina", "Action/Drama", "Star vehicle"],
  ["Papam Prathap", 2026, "Thiruveer", "S. P. Durga Naresh", "Drama/Comedy", "Breakout hit"],
  ["Gaayapadda Simham", 2026, "Tharun Bhascker", "Kasyap Sreenivas", "Comedy/Drama", "Breakout hit"],
  ["Jetlee", 2026, "Satya", "Ritesh Rana", "Crime/Comedy", "Breakout hit"],
  ["Sathi Leelavathi", 2026, "Lavanya Tripathi", "Tatineni Satya", "Drama/Thriller", "Breakout hit"],
  ["Peddi", 2026, "Ram Charan", "Buchi Babu Sana", "Sports/Drama", "Star vehicle"],
  ["Sing Geetham", 2026, "Ayaan", "Singeetam Srinivasa Rao", "Musical/Drama", "Breakout hit"],
  ["Maa Inti Bangaaram", 2026, "Samantha Ruth Prabhu", "Nandini Reddy", "Family/Drama", "Breakout hit"],
  ["Nagabandham: The Secret Treasure", 2026, "Virat Karrna", "Abhishek Nama", "Adventure/Fantasy", "Breakout hit"],
  ["Rao Bahadur", 2026, "Satyadev", "Venkatesh Maha", "Period/Drama", "Cult favourite"],
  ["Lenin", 2026, "Akhil Akkineni", "Murali Kishor Abburu", "Action/Drama", "Breakout hit"],
  ["Oh..! Sukumari", 2026, "Thiruveer", "Bharat Dharshan", "Comedy/Drama", "Breakout hit"],
  ["Chennai Love Story", 2026, "Kiran Abbavaram", "Ravi Namburii", "Romance/Drama", "Breakout hit"],
  ["Srinivasa Mangapuram", 2026, "Jaya Krishna Ghattamaneni", "Ajay Bhupathi", "Romance/Drama", "Breakout hit"],
  ["Korean Kanakaraju", 2026, "Varun Tej", "Merlapaka Gandhi", "Comedy/Action", "Star vehicle"],
];
